import SwiftUI

/// The derivation trail under persona-generated content: which model spoke,
/// what it was grounded in, licensed lineage, and the moderation verdict —
/// nothing the platform emits is a black box.
struct ProvenanceFooter: View {
    let provenance: ContentProvenance

    var body: some View {
        VStack(alignment: .leading, spacing: 3) {
            Divider().overlay(Theme.line)
            Text("Generated by \(provenance.generated_by) · grounded in persona + \(provenance.grounded_in.source_items) source item(s) · moderation: \(provenance.moderation.status)")
                .font(.caption2).foregroundStyle(Theme.t2)
            if let lineage = provenance.licensed_from {
                Text("licensed from \(lineage)").font(.caption2).foregroundStyle(Theme.amber)
            }
            Text(provenance.disclaimer).font(.caption2).foregroundStyle(Theme.t3)
        }
    }
}
