#!/usr/bin/env python3
"""Generate the README's hero art — GENERATED, do not hand-edit the output.

    python3 tools/build_assets.py

The cover used to be a hand-built one-off, and it aged exactly the way
hand-built one-offs do: it was drawn before live desks, beacons, the audience
layer, the marketplace and the burned-in AI mark existed, and it still showed
the v0.1.0 product four releases later. It was also off-palette — amber on
navy, while every screen in `docs/screens/` is night-indigo with neon purple.

So it is generated now, from the same palette constants the screens use, for
the same reason those are generated: a picture of the product that cannot be
regenerated is a picture that will be wrong soon and nobody will notice.

Dependency-free, like `docs/screens/build.py` — stdlib only, so anyone can
regenerate without installing anything.
"""

from __future__ import annotations

import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "assets", "design")

# Straight from docs/screens/build.py — one palette for the whole product, so
# the cover cannot drift away from the screens it is advertising.
C = {
    "scrA": "#181235", "scrB": "#0c0920",
    "card": "#201a48", "card2": "#181240", "line": "#302a60",
    "txt": "#f2effc", "t2": "#9a93c6", "t3": "#6a6399",
    "brandA": "#7b5cff", "brandB": "#9d7bff",
    "amber": "#ffb84d", "green": "#7bc47f", "cyan": "#9fd8e8", "red": "#e0687a",
}

W, H = 1280, 640


def esc(s: str) -> str:
    return (s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def text(x, y, s, size=14, fill=None, weight=400, anchor="start", spacing=0):
    ls = f' letter-spacing="{spacing}"' if spacing else ""
    return (f'<text x="{x}" y="{y}" font-size="{size}" fill="{fill or C["txt"]}"'
            f' font-weight="{weight}" text-anchor="{anchor}"{ls}>{esc(s)}</text>')


def rrect(x, y, w, h, r, fill, stroke=None, sw=1):
    st = f' stroke="{stroke}" stroke-width="{sw}"' if stroke else ""
    return (f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="{r}"'
            f' fill="{fill}"{st}/>')


def circle(cx, cy, r, fill="none", stroke=None, sw=1, dash=None):
    st = f' stroke="{stroke}" stroke-width="{sw}"' if stroke else ""
    da = f' stroke-dasharray="{dash}"' if dash else ""
    return f'<circle cx="{cx}" cy="{cy}" r="{r}" fill="{fill}"{st}{da}/>'


def person(cx, cy, s, fill, opacity=1.0):
    """The product's own glyph: a head and shoulders, nothing more."""
    return (f'<g opacity="{opacity}">'
            f'<circle cx="{cx}" cy="{cy - 7 * s}" r="{5.4 * s}" fill="{fill}"/>'
            f'<path d="M{cx - 9 * s} {cy + 10 * s} a{9 * s} {9.5 * s} 0 0 1 '
            f'{18 * s} 0 Z" fill="{fill}"/></g>')


def chip(x, y, label, tint):
    """A capability chip. Width is measured off the label so nothing collides —
    the defect that bit the phone screens twice."""
    w = 22 + len(label) * 6.6
    return (rrect(x, y, w, 28, 14, "rgba(255,255,255,0.04)", tint, 1)
            + text(x + w / 2, y + 18.5, label, 11.5, tint, 600, "end"
                   if False else "middle")), w + 10


def head(title, desc):
    return (
        f'<svg role="img" aria-labelledby="t d" xmlns="http://www.w3.org/2000/svg"'
        f' viewBox="0 0 {W} {H}" width="{W}" height="{H}"'
        f' font-family="Helvetica, Arial, sans-serif">'
        f'<title id="t">{esc(title)}</title><desc id="d">{esc(desc)}</desc>'
        f'<defs>'
        f'<linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">'
        f'<stop offset="0" stop-color="{C["scrA"]}"/>'
        f'<stop offset="1" stop-color="{C["scrB"]}"/></linearGradient>'
        f'<linearGradient id="brand" x1="0" y1="0" x2="1" y2="0">'
        f'<stop offset="0" stop-color="{C["brandA"]}"/>'
        f'<stop offset="1" stop-color="{C["brandB"]}"/></linearGradient>'
        f'<radialGradient id="glow" cx="50%" cy="50%" r="50%">'
        f'<stop offset="0" stop-color="{C["brandB"]}" stop-opacity="0.42"/>'
        f'<stop offset="1" stop-color="{C["brandB"]}" stop-opacity="0"/>'
        f'</radialGradient>'
        f'</defs>'
        f'<rect width="{W}" height="{H}" fill="url(#bg)"/>')


def wordmark(x, y, name, tagline, sub=None):
    o = [text(x, y, name, 54, C["txt"], 800, spacing=6),
         rrect(x + 3, y + 16, 96, 4, 2, "url(#brand)"),
         text(x, y + 48, tagline, 17, C["t2"], 400)]
    if sub:
        o.append(text(x, y + 74, sub, 13.5, C["t3"], 400))
    return "".join(o)


def cover() -> str:
    """The product as it stands: a profile that adapts to who is asking, and —
    since v0.1.7 — a live desk a real person can be summoned to."""
    o = [head("QRME — AI synthetic profile platform",
              "QRME: relationship-aware AI synthetic profiles, live desks, "
              "and a marketplace. Generated by tools/build_assets.py.")]

    # The orb sits centre-right so the wordmark column above it stays clear —
    # the first draft put the dotted ring straight through the tagline.
    cx, cy = 640, 350
    o.append(f'<circle cx="{cx}" cy="{cy}" r="200" fill="url(#glow)"/>')
    o.append(circle(cx, cy, 132, "none", C["line"], 1.4))
    o.append(circle(cx, cy, 164, "none", C["line"], 1, "3 7"))
    o.append(person(cx, cy - 6, 5.0, "url(#brand)"))

    # The AI mark rides on the portrait itself, which is the whole point of it
    # — a screenshot carries the disclosure. So it rides on the cover too.
    o.append(rrect(cx - 32, cy + 62, 64, 26, 13, "rgba(12,9,32,0.86)",
                   C["brandB"], 1.2))
    o.append(text(cx, cy + 79.5, "AI", 13, C["brandB"], 800, "middle",
                  spacing=2))

    # Who the profile is talking to changes how it behaves. One column on the
    # right, so the relationships read top-to-bottom instead of crowding the orb.
    rx = 1010
    for label, ry, tint in (("family", 196, C["brandB"]),
                            ("friend", 350, C["cyan"]),
                            ("stranger", 504, C["t3"])):
        # Bow the curve away from the orb rather than cutting straight across:
        # a Q control point pulled toward the orb's own y keeps the three arcs
        # from reading as one flat fan.
        o.append(f'<path d="M{cx + 168} {cy + (ry - cy) * 0.22} '
                 f'Q{(cx + rx) / 2} {cy + (ry - cy) * 0.86} {rx - 30} {ry}"'
                 f' fill="none" stroke="{tint}" stroke-width="1.7"'
                 f' opacity="0.55"/>')
        o.append(person(rx, ry, 2.6, tint, 0.92))
        o.append(text(rx + 40, ry + 5, label, 13.5, tint, 600))

    o.append(wordmark(86, 96, "QRME",
                      "AI synthetic profiles — relationship-aware, remembered",
                      "…and live desks a real person can be called back to"))

    # What actually shipped, named rather than implied. Wrapped into the left
    # column so it fills the space under the wordmark instead of leaving a
    # band of empty gradient across the middle.
    x, y = 86, 244
    for label, tint in (("34 starter profiles", C["brandB"]),
                        ("live desks", C["cyan"]),
                        ("desk beacons", C["green"]),
                        ("audience layer", C["amber"]),
                        ("marketplace", C["t2"]),
                        ("gifts", C["red"])):
        svg, adv = chip(x, y, label, tint)
        if x + adv > 470:                     # wrap inside the left column
            x, y = 86, y + 40
            svg, adv = chip(x, y, label, tint)
        o.append(svg)
        x += adv

    o.append(text(86, 566, "The AI mark is burned into every portrait's own",
                  12.5, C["t3"]))
    o.append(text(86, 586, "pixels — it survives a screenshot, a crop, a",
                  12.5, C["t3"]))
    o.append(text(86, 606, "hotlink, and every page that shows one.",
                  12.5, C["t3"]))
    o.append("</svg>")
    return "".join(o)


ASSETS = {"00-cover.svg": cover}


def main() -> None:
    os.makedirs(OUT, exist_ok=True)
    for name, fn in ASSETS.items():
        path = os.path.join(OUT, name)
        with open(path, "w") as f:
            f.write(fn())
        print(f"wrote assets/design/{name}")


if __name__ == "__main__":
    main()
