#!/usr/bin/env python3
"""Regenerate ``docs/screens/textwidth.py`` by measuring rendered glyphs.

Run this if the screens' font stack changes. It needs ``cairosvg`` and
``pillow``, neither of which is a dependency of the package — this is a tool
that produces a checked-in table, not something the build or the tests import.

    python3 tools/measure_text.py

The method: render ``H<char × 20>H`` at a large size, take the ink extent, and
subtract the extent of ``HH``. What is left is twenty advances. Two things that
went wrong the first time and are worth keeping in view:

* **Whitespace collapses in SVG text**, so twenty spaces render as one. A
  space is measured against a control string instead — ``x x x…`` versus
  ``xxx…`` — where the single spaces survive.
* **Cairo substitutes DejaVu Sans**, which is wider than any of SF Pro, Segoe
  UI or Roboto that a browser will actually find. The resulting table
  over-estimates a little, which is the safe direction for a check whose job
  is to stop text running off the edge.
"""

from __future__ import annotations

import html
import io
import string
import sys
from pathlib import Path

import cairosvg
from PIL import Image

FONT = ("-apple-system,BlinkMacSystemFont,'SF Pro Display','SF Pro Text',"
        "'Segoe UI',Roboto,system-ui,sans-serif")
SIZE = 100.0
WEIGHTS = (400, 500, 600, 650, 700, 750, 800)
CHARS = (string.ascii_letters + string.digits
         + ".,:;!?&%$#@()[]{}/\\|+-_=*'\"<>~^`"
         + "·—–→⟷“”’…°")
OUT = Path(__file__).resolve().parent.parent / "docs/screens/textwidth.py"

HEADER = '''"""How wide a string is, before it is drawn.

The screens are hand-laid SVG: nothing wraps, nothing ellipsises, and a label
that is too long simply runs off the side of the phone. Three of them did
exactly that on the gaming screen and survived a full gallery rebuild, because
the only thing that would have caught it was somebody happening to look at that
one screen.

A character count does not catch it — ``Companion`` and ``lllllllll`` are both
nine characters and one is nearly twice as wide. So this is a real advance-width
table, per character and per weight, in units of the font size.

Generated by ``tools/measure_text.py`` — do not edit by hand. Accurate to
within half a percent against a rendered measurement, and biased very slightly
wide, which is the direction an overflow check should err in.
"""

from __future__ import annotations

'''


def ink_right(markup: str, weight: int) -> float:
    svg = (f'<svg xmlns="http://www.w3.org/2000/svg" width="12000" height="300">'
           f'<rect width="12000" height="300" fill="#000"/>'
           f'<text x="20" y="200" font-family="{FONT}" font-size="{SIZE}" '
           f'font-weight="{weight}" fill="#fff">{markup}</text></svg>')
    im = Image.open(io.BytesIO(
        cairosvg.svg2png(bytestring=svg.encode()))).convert("L")
    box = im.getbbox()
    return box[2] if box else 20.0


def measure(weight: int) -> dict[str, float]:
    base = ink_right("HH", weight)
    row = {c: round((ink_right("H" + html.escape(c) * 20 + "H", weight) - base)
                    / 20.0 / SIZE, 5) for c in CHARS}
    row[" "] = round((ink_right("H" + "x " * 20 + "xH", weight)
                      - ink_right("H" + "x" * 21 + "H", weight))
                     / 20.0 / SIZE, 5)
    return row


def main() -> int:
    parts = [HEADER,
             "# advance width per character, as a fraction of the font size\n"
             "WIDTHS: dict[int, dict[str, float]] = {\n"]
    for weight in WEIGHTS:
        row = measure(weight)
        parts.append(f"    {weight}: {{\n")
        line = "        "
        for char, adv in sorted(row.items()):
            piece = f"{char!r}: {adv}, "
            if len(line) + len(piece) > 76:
                parts.append(line.rstrip() + "\n")
                line = "        "
            line += piece
        parts.append(line.rstrip().rstrip(",") + ",\n    },\n")
    parts.append("}\n\nFALLBACK = 0.6      # an unmeasured glyph, assumed wide\n"
                 "\n\n")
    parts.append('''def width(s: str, size: float, weight: int = 400) -> float:
    """Width of `s` in px at `size`, in the screens' font stack.

    An unlisted weight falls back to the nearest measured one rather than
    raising: the answer stays approximately right, which is all a layout check
    needs, and a KeyError here would break a build over a font weight.
    """
    row = WIDTHS.get(weight)
    if row is None:
        row = WIDTHS[min(WIDTHS, key=lambda w: abs(w - weight))]
    return sum(row.get(ch, FALLBACK) for ch in s) * size
''')
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"wrote {OUT} — {len(WEIGHTS)} weights, {len(CHARS) + 1} glyphs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
