"""The occupations themselves, by family.

Read as a table, not as code: a family line says what everyone in it shares,
and each role adds only what makes it that role. Nothing here is imported
from a taxonomy — see the note in `build_occupations.py`.

Skills are written as a **digital** worker's skills: the things a synthetic
one does with a keyboard, a model and a set of doors. Connections are the
people and systems it must be able to reach to finish the work, because a
role that cannot reach its escalation is a role that stalls.
"""


#: How somebody asks for a job whose name they do not know. The search bar
#: is the way into the pool, and "reads scans" has to reach the radiologist
#: — a person who already knows the word "radiologist" did not need a pool.
#: Layman words attached by a word in the title rather than by the whole
#: title. `SYNONYMS` names one row at a time, which is right for the roles
#: written out by hand and useless for the thousand taxonomy titles folded
#: in beside them — "Dental Hygienists" arrived with the word "teeth"
#: nowhere on it, so somebody typing "cleans teeth" was shown a building
#: cleaner. A stem here reaches every row whose title contains it, written
#: or imported.
WORD_SYNONYMS = {
    "dental": "teeth tooth mouth",
    "dentist": "teeth tooth fillings mouth",
    "dental hygienist": "cleans teeth tooth scale polish mouth",
    "orthodont": "braces teeth straighten",
    "optometr": "eye test glasses sight vision",
    "optician": "glasses lenses eye sight",
    "ophthalmolog": "eye surgery sight",
    "audiolog": "hearing ears deaf",
    "podiatr": "feet foot toenails",
    "dermatolog": "skin rash mole",
    "cardiolog": "heart",
    "neurolog": "brain nerves",
    "oncolog": "cancer tumour tumor",
    "psychiatr": "mental health mind",
    "psycholog": "mind therapy behaviour behavior",
    "pediatric": "children kids babies",
    "paediatric": "children kids babies",
    "obstetric": "pregnancy birth babies",
    "midwi": "delivers babies birth pregnancy labour",
    "veterinar": "animals pets vet",
    "pharmac": "medicines drugs prescriptions chemist",
    "radiolog": "reads scans x-ray imaging",
    "radiograph": "x-ray scans imaging",
    "sonograph": "ultrasound scans",
    "anesthesiolog": "anaesthetic asleep surgery",
    "anaesthesiolog": "anaesthetic asleep surgery",
    "surgeon": "operates surgery cuts",
    "nurse": "ward hospital bedside patients",
    "paramedic": "ambulance emergency rescue",
    "physiotherap": "physio rehabilitation movement injury",
    "dietit": "food diet nutrition eating",
    "dietic": "food diet nutrition eating",
    "pilot": "flies planes flying aircraft cockpit",
    "aviation": "planes aircraft flying",
    "locomotive": "trains driving rail",
    "conductor": "trains tickets passengers",
    "captain": "ship boat sailing command",
    "mariner": "ship boat sailing sea",
    "trucker": "lorry haulage driving",
    "truck": "lorry haulage driving",
    "chauffeur": "driving car passengers",
    "courier": "delivers parcels packages",
    "postal": "post mail letters delivery",
    "plumber": "fixes pipes leaks boiler taps drains",
    "electrician": "wiring sockets fuse box lights power",
    "carpenter": "wood joinery timber",
    "roofer": "roof tiles slates guttering",
    "mason": "bricks walls mortar stone",
    "glazier": "glass windows glazing",
    "welder": "welding joining metal",
    "welding": "joins metal",
    "machinist": "machines metal cutting lathe",
    "mechanic": "fixes cars engines repairs vehicles",
    "millwright": "machinery installs repairs",
    "locksmith": "locks keys doors",
    "upholster": "furniture fabric sofa",
    "tailor": "clothes alterations sewing",
    "seamstress": "sewing clothes stitching",
    "cobbler": "shoes repairs",
    "shoemaker": "shoes making",
    "jewel": "rings gold silver stones",
    "barber": "cuts hair men beard shave",
    "hairdress": "cuts hair salon colour",
    "cosmetolog": "hair beauty nails skin",
    "manicur": "nails hands",
    "esthetic": "facials skin beauty",
    "chef": "cooks food kitchen restaurant",
    "cook": "cooks food kitchen meals",
    "baker": "bread cakes pastry oven",
    "butcher": "meat cuts joints",
    "bartend": "drinks bar cocktails",
    "waiter": "serves tables restaurant",
    "waitress": "serves tables restaurant",
    "barista": "coffee espresso cafe",
    "cashier": "till checkout payments",
    "farmer": "grows crops fields livestock land",
    "agricultur": "farming crops land",
    "forester": "trees woodland timber",
    "logging": "trees felling timber",
    "fisher": "fishing boats catch sea",
    "zookeep": "animals zoo keeper",
    "groundskeep": "grounds grass lawns",
    "landscap": "gardens grounds planting",
    "firefight": "puts out fires rescue engine",
    "fire-fighter": "puts out fires rescue engine",
    "police": "arrests crime patrol law enforcement",
    "detective": "investigates crime cases",
    "correctional": "prison inmates custody",
    "bailiff": "court enforcement",
    "lifeguard": "swimming rescue pool beach",
    "lawyer": "legal court advice cases",
    "attorney": "legal court advice cases",
    "solicitor": "legal advice contracts wills",
    "barrister": "argues court advocate trial",
    "judge": "court rulings sentencing",
    "paralegal": "legal research documents",
    "notar": "witnesses signatures documents",
    "accountant": "accounts tax books financial numbers",
    "bookkeep": "books ledger invoices accounts",
    "auditor": "checks accounts audit",
    "actuar": "risk statistics insurance numbers",
    "underwrit": "insurance risk policies",
    "appraiser": "values property valuation",
    "assessor": "values property valuation",
    "teller": "bank counter cash",
    "teacher": "teaches classroom pupils school",
    "professor": "teaches university students lectures",
    "lecturer": "teaches university students lectures",
    "librarian": "books library lending",
    "archivist": "records archives preservation",
    "curator": "museum collection exhibits",
    "architect": "designs buildings plans drawings",
    "civil engineer": "designs bridges roads tunnels structures",
    "structural": "designs bridges buildings structures loads",
    "construction": "builds buildings houses site",
    "bricklayer": "builds walls houses bricks",
    "brickmason": "builds walls houses bricks",
    "surveyor": "measures land boundaries surveys",
    "drafter": "drawings plans technical",
    "programmer": "writes code software",
    "developer": "writes code software builds",
    "software": "code programming applications",
    "database": "data tables queries storage",
    "cybersecurity": "security hacking defence protection",
    "penetration": "hacking security testing",
    "influencer": "online social media following posts",
    "creator": "online content posts videos making",
    "streamer": "live online streaming broadcast",
    "podcast": "audio show episodes talking",
    "webcam": "online camera live",
    "estate agent": "sells houses property viewings",
    "realtor": "sells houses property viewings",
    "receptionist": "front desk visitors calls",
    "janitor": "cleaning building caretaker",
    "welder": "welding joining metal",
}


SYNONYMS = {
    "Radiologist": "reads scans x-ray xray mri ct imaging pictures inside body",
    "Sonographer": "ultrasound scan baby scan pregnancy imaging",
    "Airline pilot": "flies planes flying aircraft aeroplane airplane cockpit captain",
    "Air traffic controller": "guides planes airspace tower radar landing",
    "Criminal defence lawyer": "defends people court trial accused criminal defence",
    "Barrister": "argues court advocate trial wig robes",
    "Solicitor": "legal advice contracts conveyancing wills",
    "Care home manager": "looks after old people elderly residential care nursing home",
    "Support worker": "looks after old people elderly disabled daily living help",
    "Registered nurse": "nurse ward hospital bedside patients",
    "Paramedic": "ambulance emergency 999 911 rescue",
    "Firefighter": "puts out fires rescue engine brigade",
    "Police officer": "arrests crime patrol law enforcement cop",
    "Plumber": "fixes pipes leaks boiler bathroom taps drains",
    "Electrician": "wiring sockets fuse box rewire lights power",
    "Carpenter": "wood joinery framing timber",
    "Roofer": "roof tiles slates leaks guttering",
    "Bricklayer": "bricks walls mortar masonry",
    "Auto mechanic": "fixes cars garage engine service mot repair vehicles",
    "Hairdresser": "cuts hair salon colour styling",
    "Barber": "cuts hair men beard shave",
    "Chef": "cooks food kitchen restaurant meals",
    "Baker": "bread cakes pastry oven",
    "Butcher": "meat cuts joints carcass",
    "Farmer": "grows crops fields livestock tractor land",
    "Veterinarian": "animal doctor vet pets treats animals",
    "Dentist": "teeth fillings dental mouth",
    "Optometrist": "eye test glasses vision sight",
    "Pharmacist": "medicines chemist prescriptions drugs dispensing",
    "Physiotherapist": "physio rehabilitation movement injury recovery",
    "Psychiatrist": "mental health medication psychiatric doctor mind",
    "Clinical psychologist": "therapy mental health assessment mind talking",
    "Counsellor": "talking therapy listening support mental health",
    "Social worker": "families children safeguarding vulnerable support services",
    "Midwife": "delivers babies birth pregnancy labour maternity",
    "Primary school teacher": "teaches children school classroom pupils young",
    "Secondary school teacher": "teaches teenagers school subject classroom",
    "University lecturer": "teaches students university higher education academic",
    "Accountant": "accounts tax books financial statements numbers",
    "Bookkeeper": "books ledger invoices day to day accounts",
    "Estate agent": "sells houses property viewings valuations realtor",
    "Architect": "designs buildings plans drawings",
    "Software engineer": "writes code programming developer software",
    "Data scientist": "analyses data models statistics machine learning",
    "Security guard": "guards premises patrol watch security",
    "Cleaner": "cleans cleaning janitor housekeeping",
    "Truck driver": "drives lorry hgv haulage freight long distance",
    "Delivery driver": "delivers parcels van courier drop off",
    "Bus driver": "drives bus passengers route public transport",
    "Train driver": "drives train rail locomotive",
    "Ship captain": "sails ship master vessel sea navigation",
    "Welder": "welding joins metal fabrication torch",
    "Machinist": "machining lathe cnc milling metal parts",
    "Warehouse operative": "picking packing warehouse stock shelves",
    "Forklift operator": "forklift pallets warehouse lifting",
    "Receptionist": "front desk answers phone greets visitors reception",
    "Customer service representative": "call centre helpdesk customer support complaints",
    "Sales representative": "sells selling sales targets customers",
    "Recruiter": "hiring recruitment candidates interviews staffing",
    "Journalist": "writes news reporter articles press",
    "Photographer": "takes photos camera shoots pictures",
    "Video editor": "edits video footage cutting post production",
    "Graphic designer": "designs logos artwork layouts visual",
    "Musician": "plays music instrument performs band",
    "Actor": "acts performs stage screen drama",
    "Personal trainer": "fitness gym training exercise coaching",
    "Funeral director": "funerals undertaker burial cremation bereaved",
    "Tour guide": "shows visitors around sightseeing tours",
    "Translator": "translates languages written translation",
    "Interpreter": "interprets languages spoken live translation",
    "Librarian": "books library lending cataloguing readers",
    "Zookeeper": "looks after animals zoo enclosures",
    "Beekeeper": "bees hives honey apiary",
    "Fisher": "fishing boat catch sea trawler",
    "Forester": "trees woodland forestry felling",
    "Miner": "",
    "Electrical engineer": "electrical design power systems circuits",
    "Civil engineer": "roads bridges infrastructure structures",
    "Patent attorney": "patents inventions filing intellectual property",
    "Data protection officer": "gdpr privacy data protection compliance",
    "Chief executive": "ceo runs company boss leader top",
    "Project manager": "runs projects deadlines delivery coordination",
    "Human resources manager": "hr people staff employment personnel",
    "Office manager": "runs office admin facilities supplies",
    "Executive assistant": "pa personal assistant diary executive support",
}


def load(family):
    # ---- Health care -----------------------------------------------------
    family("Health care",
           "patient history intake;clinical note writing;coded record keeping;"
           "triage by severity;consent capture;privacy handling",
           "patients;nursing staff;medical records;pharmacy;billing office",
           {
        "Physician": ("differential diagnosis;prescription drafting;referral letters", "specialists;labs"),
        "Family physician": ("longitudinal care planning;preventive screening recall", "community services"),
        "Internist": ("chronic disease management;medication reconciliation", "specialists"),
        "Paediatrician": ("growth chart reading;immunisation scheduling", "parents;schools"),
        "Cardiologist": ("ECG interpretation;risk scoring", "cath lab;imaging"),
        "Dermatologist": ("lesion description;biopsy request drafting", "pathology"),
        "Neurologist": ("neuro exam documentation;seizure log review", "imaging;EEG technicians"),
        "Oncologist": ("staging documentation;regimen tracking", "tumour board;pharmacy"),
        "Psychiatrist": ("mental status examination;risk assessment", "therapists;crisis services"),
        "Radiologist": ("image report dictation;prior study comparison", "imaging technologists;referrers"),
        "Anaesthesiologist": ("pre-operative assessment;airway risk scoring", "surgeons;recovery unit"),
        "Surgeon": ("operative note writing;consent explanation", "theatre staff;anaesthesia"),
        "Orthopaedic surgeon": ("fracture classification;rehabilitation planning", "physiotherapists"),
        "Obstetrician": ("antenatal record keeping;labour progress charting", "midwives"),
        "Emergency physician": ("rapid triage;disposition decisions", "ambulance crews;admitting teams"),
        "Pathologist": ("specimen report writing;result release", "laboratory;clinicians"),
        "Ophthalmologist": ("visual acuity recording;field test review", "optometrists"),
        "Dentist": ("dental charting;treatment planning", "dental hygienists;labs"),
        "Orthodontist": ("appliance planning;progress photography review", "dentists"),
        "Veterinarian": ("species-specific history taking;owner instruction writing", "owners;animal labs"),
        "Pharmacist": ("interaction checking;dispensing record keeping;counselling notes", "prescribers;insurers"),
        "Physiotherapist": ("movement assessment;exercise programme writing", "physicians;patients"),
        "Occupational therapist": ("activity analysis;adaptation planning", "families;employers"),
        "Speech therapist": ("communication assessment;practice plan writing", "schools;families"),
        "Dietitian": ("intake analysis;meal plan writing", "physicians;catering"),
        "Optometrist": ("refraction recording;lens prescribing", "opticians"),
        "Podiatrist": ("gait notes;orthotic specification", "orthotists"),
        "Chiropractor": ("spinal assessment notes;treatment logging", "physicians"),
        "Midwife": ("birth plan drafting;postnatal checks", "obstetricians;health visitors"),
        "Paramedic": ("scene report writing;protocol-driven treatment logging", "dispatch;emergency departments"),
        "Registered nurse": ("care plan writing;medication administration records;observation charting", "physicians;families"),
        "Nurse practitioner": ("independent assessment;prescribing within scope", "physicians"),
        "Intensive care nurse": ("ventilator chart reading;hourly observation logging", "intensivists"),
        "Theatre nurse": ("instrument count records;sterile field checks", "surgeons"),
        "Health visitor": ("developmental checks;safeguarding notes", "families;social services"),
        "Medical laboratory scientist": ("assay result validation;quality control logging", "pathologists"),
        "Radiographer": ("exposure protocol selection;image quality checks", "radiologists"),
        "Sonographer": ("scan protocol following;measurement recording", "radiologists;obstetricians"),
        "Phlebotomist": ("draw order sequencing;sample labelling", "laboratory"),
        "Medical coder": ("diagnosis coding;procedure coding;audit trail keeping", "billing;payers"),
        "Medical transcriptionist": ("dictation transcription;terminology checking", "clinicians"),
        "Clinical research coordinator": ("protocol tracking;consent documentation;adverse event logging", "sponsors;ethics boards"),
        "Hospital administrator": ("capacity reporting;policy maintenance", "department heads;regulators"),
        "Infection control officer": ("outbreak tracking;protocol publication", "wards;public health"),
        "Health information manager": ("record retention scheduling;release-of-information handling", "legal;patients"),
    })

    # ---- Mental health & social care -------------------------------------
    family("Mental health & social care",
           "case note writing;risk flagging;referral drafting;boundary keeping;"
           "confidentiality handling",
           "clients;supervisors;referral network;crisis services",
           {
        "Clinical psychologist": ("psychometric interpretation;formulation writing", "psychiatrists"),
        "Counsellor": ("session note keeping;goal tracking", "GPs"),
        "Psychotherapist": ("treatment plan writing;progress review", "supervisors"),
        "Social worker": ("assessment writing;care package coordination", "housing;schools;courts"),
        "Child protection officer": ("safeguarding record keeping;multi-agency reporting", "police;schools"),
        "Substance abuse counsellor": ("relapse plan writing;attendance tracking", "clinics;courts"),
        "Marriage and family therapist": ("genogram building;session planning", "schools"),
        "Case manager": ("service plan tracking;benefit navigation", "insurers;agencies"),
        "Crisis line responder": ("de-escalation scripting;handoff writing", "emergency services"),
        "Peer support specialist": ("recovery plan support;community signposting", "clinicians"),
        "Probation officer": ("condition monitoring;court report writing", "courts;police"),
        "Youth worker": ("activity planning;incident logging", "schools;families"),
        "Care home manager": ("staffing rota building;inspection preparation", "regulators;families"),
        "Support worker": ("daily log keeping;personal care recording", "care managers"),
    })

    # ---- Software & IT ---------------------------------------------------
    family("Software & IT",
           "version control;code review;issue tracking;technical writing;"
           "automated testing;incident write-ups",
           "product managers;designers;on-call rota;security team",
           {
        "Software engineer": ("feature implementation;refactoring;debugging", "QA"),
        "Backend engineer": ("API design;database schema work;queue handling", "SRE"),
        "Frontend engineer": ("component building;accessibility checks;state management", "designers"),
        "Full-stack engineer": ("end-to-end feature delivery;schema-to-screen tracing", "product"),
        "Mobile engineer": ("store submission;device compatibility testing", "store reviewers"),
        "iOS engineer": ("Swift implementation;App Store review handling", "Apple review"),
        "Android engineer": ("Kotlin implementation;Play Console handling", "Google Play review"),
        "Embedded engineer": ("firmware writing;hardware debugging", "hardware engineers"),
        "Game developer": ("engine scripting;asset pipeline work;playtest analysis", "artists;testers"),
        "Site reliability engineer": ("alert tuning;capacity planning;postmortem writing", "engineering teams"),
        "DevOps engineer": ("pipeline building;release automation;infrastructure as code", "developers"),
        "Platform engineer": ("internal tooling;developer experience work", "engineering teams"),
        "Cloud architect": ("topology design;cost modelling;migration planning", "finance;vendors"),
        "Database administrator": ("index tuning;backup verification;restore drills", "developers"),
        "Systems administrator": ("account provisioning;patch scheduling", "staff;vendors"),
        "Network engineer": ("routing configuration;traffic analysis", "carriers"),
        "Security engineer": ("threat modelling;dependency auditing;finding triage", "engineering;legal"),
        "Penetration tester": ("scoped testing;evidence capture;report writing", "clients;security team"),
        "Security analyst": ("alert triage;log correlation;incident escalation", "SOC;incident response"),
        "Incident responder": ("timeline reconstruction;containment coordination", "legal;communications"),
        "QA engineer": ("test plan writing;regression suites;defect reproduction", "developers"),
        "Test automation engineer": ("harness building;flake reduction", "QA;developers"),
        "Data engineer": ("pipeline building;schema evolution;data quality checks", "analysts"),
        "Data scientist": ("feature engineering;model evaluation;result communication", "product;analysts"),
        "Machine learning engineer": ("training pipeline work;inference serving;evaluation harnesses", "researchers"),
        "MLOps engineer": ("model deployment;drift monitoring;rollback handling", "SRE"),
        "Research scientist": ("literature review;experiment design;paper writing", "peers;reviewers"),
        "Prompt engineer": ("instruction design;evaluation set building;regression checking", "product;safety"),
        "Data analyst": ("query writing;dashboard building;finding narration", "stakeholders"),
        "Business intelligence developer": ("semantic layer modelling;report publishing", "finance;operations"),
        "Technical writer": ("documentation authoring;API reference upkeep;changelog editing", "engineers;support"),
        "Solutions architect": ("requirement mapping;integration design", "clients;sales"),
        "Integration engineer": ("connector building;contract testing", "partners"),
        "Release engineer": ("version stamping;changelog assembly;artefact signing", "engineering;stores"),
        "IT support technician": ("ticket handling;device imaging;access resets", "staff"),
        "Help desk analyst": ("first-line triage;knowledge base upkeep", "users;IT"),
        "Product manager": ("requirement writing;roadmap upkeep;launch coordination", "engineering;design;sales"),
        "Technical product manager": ("API roadmap;partner requirement gathering", "engineering;partners"),
        "Scrum master": ("ceremony facilitation;impediment tracking", "teams"),
        "Engineering manager": ("one-to-one records;delivery tracking;hiring loops", "reports;leadership"),
    })

    # ---- Engineering & built environment ---------------------------------
    family("Engineering & built environment",
           "specification writing;drawing review;standards compliance;"
           "calculation checking;change records",
           "clients;contractors;regulators;suppliers",
           {
        "Civil engineer": ("load calculation;site drawing markup;permit drafting", "councils"),
        "Structural engineer": ("frame analysis;material specification", "architects"),
        "Mechanical engineer": ("tolerance specification;CAD review;failure analysis", "machinists"),
        "Electrical engineer": ("circuit specification;load scheduling;compliance testing", "electricians"),
        "Chemical engineer": ("process flow specification;yield calculation", "plant operators"),
        "Aerospace engineer": ("airworthiness documentation;stress analysis", "certifiers"),
        "Automotive engineer": ("component specification;homologation paperwork", "manufacturing"),
        "Environmental engineer": ("impact assessment writing;monitoring plans", "regulators"),
        "Geotechnical engineer": ("borehole log reading;foundation recommendation", "surveyors"),
        "Marine engineer": ("vessel system specification;survey preparation", "classification societies"),
        "Petroleum engineer": ("reservoir reporting;well plan review", "rig crews"),
        "Mining engineer": ("extraction planning;ventilation calculation", "mine operations"),
        "Industrial engineer": ("process mapping;throughput analysis", "operations"),
        "Manufacturing engineer": ("line layout planning;yield tracking", "production"),
        "Quality engineer": ("inspection plan writing;non-conformance handling", "production;auditors"),
        "Reliability engineer": ("failure mode analysis;maintenance scheduling", "maintenance"),
        "Architect": ("plan drafting;planning application writing;specification", "planners;builders"),
        "Landscape architect": ("planting schedule;site plan drafting", "councils;contractors"),
        "Urban planner": ("zoning analysis;consultation reporting", "councils;communities"),
        "Surveyor": ("measurement recording;boundary reporting", "landowners"),
        "Quantity surveyor": ("cost planning;valuation certification", "contractors;clients"),
        "Building inspector": ("compliance checking;defect noting", "builders;councils"),
        "Draughtsperson": ("technical drawing production;revision control", "engineers"),
        "BIM coordinator": ("model federation;clash detection reporting", "design teams"),
        "Project engineer": ("programme tracking;RFI handling", "site teams"),
        "Construction manager": ("sequencing;subcontractor coordination;site reporting", "trades;clients"),
        "Site supervisor": ("daily site records;safety briefings", "trades"),
        "Health and safety officer": ("risk assessment writing;incident investigation", "regulators;staff"),
    })

    # ---- Finance, accounting & insurance ---------------------------------
    family("Finance, accounting & insurance",
           "ledger reading;reconciliation;report preparation;control checking;"
           "regulatory filing;audit trail keeping",
           "auditors;regulators;clients;banks",
           {
        "Accountant": ("month-end close;statement preparation", "tax office"),
        "Chartered accountant": ("statutory accounts;audit liaison", "auditors"),
        "Bookkeeper": ("transaction entry;bank reconciliation;invoice chasing", "suppliers"),
        "Financial controller": ("close ownership;variance analysis", "leadership"),
        "Chief financial officer": ("capital planning;board reporting", "board;investors"),
        "Auditor": ("sampling;working paper preparation;finding write-up", "management"),
        "Internal auditor": ("control testing;remediation tracking", "departments"),
        "Tax adviser": ("return preparation;relief identification", "tax authority"),
        "Payroll administrator": ("pay run processing;deduction handling", "staff;tax office"),
        "Credit controller": ("aged debt chasing;credit limit setting", "customers"),
        "Financial analyst": ("model building;forecast maintenance", "leadership"),
        "Investment analyst": ("company research;valuation modelling", "portfolio managers"),
        "Portfolio manager": ("allocation decisions;mandate compliance", "clients;analysts"),
        "Trader": ("order execution;position monitoring", "brokers;risk"),
        "Risk manager": ("exposure measurement;limit monitoring", "trading;board"),
        "Compliance officer": ("policy maintenance;breach investigation;regulator reporting", "regulators"),
        "Anti-money-laundering analyst": ("transaction monitoring;suspicious activity reporting", "regulators"),
        "Actuary": ("reserve calculation;pricing model maintenance", "underwriters"),
        "Underwriter": ("risk appraisal;policy terms setting", "brokers"),
        "Insurance broker": ("cover comparison;client advising", "insurers;clients"),
        "Claims adjuster": ("claim investigation;settlement recommendation", "claimants;repairers"),
        "Loss adjuster": ("damage assessment;report writing", "insurers"),
        "Mortgage adviser": ("affordability assessment;product comparison", "lenders;buyers"),
        "Bank teller": ("transaction processing;identity checking", "customers"),
        "Relationship manager": ("portfolio reviews;product introduction", "clients"),
        "Treasury analyst": ("cash positioning;facility monitoring", "banks"),
        "Procurement officer": ("tender running;supplier evaluation", "suppliers;legal"),
        "Financial planner": ("goal-based planning;portfolio review", "clients"),
    })

    # ---- Law & public administration --------------------------------------
    family("Law & public administration",
           "statute reading;precedent research;document drafting;deadline tracking;"
           "privilege handling;file note keeping",
           "clients;courts;opposing counsel;regulators",
           {
        "Solicitor": ("contract drafting;client advising;matter management", "barristers"),
        "Barrister": ("advocacy preparation;opinion writing", "solicitors;courts"),
        "Corporate lawyer": ("transaction documentation;due diligence review", "boards"),
        "Litigation lawyer": ("pleading drafting;disclosure review", "courts;experts"),
        "Employment lawyer": ("policy review;tribunal preparation", "HR"),
        "Immigration lawyer": ("application preparation;status tracking", "authorities"),
        "Family lawyer": ("settlement drafting;welfare submissions", "courts;social services"),
        "Criminal defence lawyer": ("evidence review;mitigation drafting", "police;courts"),
        "Intellectual property lawyer": ("filing strategy;infringement analysis", "patent offices"),
        "Patent attorney": ("specification drafting;prosecution response writing", "examiners;inventors"),
        "Trademark attorney": ("clearance searching;opposition handling", "registries"),
        "Paralegal": ("bundle preparation;research summaries;filing", "lawyers;courts"),
        "Legal secretary": ("diary management;document formatting", "lawyers"),
        "Contract manager": ("obligation tracking;variation handling", "suppliers"),
        "Notary": ("identity verification;deed certification", "clients"),
        "Judge": ("judgment writing;hearing management", "counsel;registry"),
        "Court clerk": ("listing;record keeping", "judges;parties"),
        "Prosecutor": ("charging decisions;case preparation", "police;courts"),
        "Policy analyst": ("evidence review;option appraisal;briefing writing", "ministers;stakeholders"),
        "Civil servant": ("correspondence handling;submission drafting", "ministers;public"),
        "Data protection officer": ("record of processing upkeep;breach assessment;subject request handling", "regulators;staff"),
        "Records manager": ("retention scheduling;disposal authorisation", "departments"),
        "Licensing officer": ("application assessment;condition setting", "applicants"),
        "Planning officer": ("application review;committee reporting", "developers;public"),
        "Elections officer": ("register maintenance;count administration", "candidates;public"),
    })

    # ---- Education & research ---------------------------------------------
    family("Education & research",
           "lesson or session planning;assessment writing;progress recording;"
           "feedback drafting;safeguarding awareness",
           "learners;parents or sponsors;colleagues;examination boards",
           {
        "Primary school teacher": ("phonics teaching;differentiation planning", "parents"),
        "Secondary school teacher": ("subject scheme writing;exam preparation", "exam boards"),
        "Special educational needs coordinator": ("support plan writing;provision mapping", "specialists;parents"),
        "Teaching assistant": ("small group support;progress noting", "teachers"),
        "Head teacher": ("staffing;inspection preparation;budget oversight", "governors;inspectors"),
        "University lecturer": ("curriculum design;marking;supervision", "students;faculty"),
        "Professor": ("research direction;grant writing;peer review", "funders;journals"),
        "Postdoctoral researcher": ("experiment running;paper drafting", "principal investigator"),
        "Research assistant": ("data collection;literature searching", "researchers"),
        "Laboratory technician": ("equipment preparation;sample handling;log keeping", "scientists"),
        "Academic advisor": ("progression review;referral to support", "students;faculty"),
        "Admissions officer": ("application assessment;offer issuing", "applicants"),
        "Curriculum developer": ("outcome mapping;material authoring", "teachers;publishers"),
        "Instructional designer": ("course structuring;assessment design;media briefing", "subject experts"),
        "Corporate trainer": ("workshop delivery;competency tracking", "managers;staff"),
        "Careers adviser": ("guidance interviews;opportunity matching", "employers;learners"),
        "Librarian": ("cataloguing;acquisition;reference support", "readers;publishers"),
        "Archivist": ("appraisal;finding aid writing;preservation planning", "researchers"),
        "Museum curator": ("collection documentation;exhibition planning", "conservators;public"),
        "Conservator": ("condition reporting;treatment recording", "curators"),
        "Examinations officer": ("timetabling;access arrangement handling", "boards;candidates"),
        "Education inspector": ("evidence gathering;report writing", "schools;authorities"),
    })

    # ---- Skilled trades ---------------------------------------------------
    family("Skilled trades",
           "job sheet keeping;materials estimating;quotation drafting;"
           "regulation compliance;certificate issuing",
           "customers;suppliers;inspectors;other trades",
           {
        "Electrician": ("circuit testing records;installation certification", "building control"),
        "Plumber": ("pipework specification;pressure test logging", "gas inspectors"),
        "Gas engineer": ("appliance servicing records;safety certification", "regulators"),
        "Carpenter": ("cutting lists;setting-out", "joiners;builders"),
        "Joiner": ("bespoke unit drawing;finish specification", "carpenters"),
        "Bricklayer": ("bond setting-out;quantity take-off", "builders"),
        "Plasterer": ("surface preparation notes;coverage estimating", "decorators"),
        "Painter and decorator": ("surface schedule;colour specification", "clients"),
        "Roofer": ("weatherproofing detail;access planning", "scaffolders"),
        "Scaffolder": ("erection plans;inspection records", "site managers"),
        "Welder": ("procedure specification following;weld log keeping", "inspectors"),
        "Machinist": ("programme setting;tolerance verification", "engineers"),
        "Fabricator": ("cut plans;assembly sequencing", "welders"),
        "Toolmaker": ("die specification;maintenance records", "production"),
        "HVAC technician": ("system commissioning records;refrigerant logging", "regulators"),
        "Refrigeration engineer": ("load calculation;service history keeping", "food operators"),
        "Locksmith": ("access record keeping;identity checking", "customers;police"),
        "Glazier": ("measurement recording;specification of glass units", "builders"),
        "Tiler": ("setting-out;adhesive specification", "builders"),
        "Flooring installer": ("subfloor assessment;quantity estimating", "suppliers"),
        "Landscaper": ("planting schedules;maintenance plans", "clients;nurseries"),
        "Arborist": ("tree survey recording;work specification", "councils"),
        "Groundworker": ("excavation records;service avoidance checks", "utilities"),
        "Demolition operative": ("method statement following;waste recording", "regulators"),
        "Steel erector": ("lift planning;bolt-up records", "engineers"),
        "Crane operator": ("lift plan reading;load charting", "riggers;site managers"),
        "Plant operator": ("machine checks;fuel and hours logging", "site managers"),
        "Auto mechanic": ("fault diagnosis;service history keeping;parts ordering", "customers;parts suppliers"),
        "Auto electrician": ("circuit diagnosis;module coding records", "workshops"),
        "Panel beater": ("damage assessment;repair method recording", "insurers"),
        "Vehicle inspector": ("roadworthiness checking;defect reporting", "authorities"),
        "Motorcycle technician": ("service scheduling;recall checking", "customers"),
        "Aircraft maintenance engineer": ("maintenance record keeping;airworthiness release", "regulators;airlines"),
        "Marine engineer technician": ("engine log keeping;survey preparation", "surveyors"),
        "Wind turbine technician": ("service records;fault code interpretation", "operators"),
        "Solar installer": ("array specification;commissioning records", "grid operators"),
        "Telecoms engineer": ("line testing;installation records", "network operations"),
        "Cable jointer": ("joint records;safety isolation checks", "network operators"),
        "Lift engineer": ("service records;statutory inspection support", "inspectors"),
        "Boilermaker": ("pressure part records;weld traceability", "inspectors"),
        "Upholsterer": ("fabric estimating;frame assessment", "clients"),
        "Cabinetmaker": ("cut lists;finish scheduling", "designers"),
        "Blacksmith": ("forge scheduling;material specification", "clients"),
        "Stonemason": ("template making;material selection", "conservation officers"),
        "Signwriter": ("layout proofing;material specification", "clients"),
    })

    # ---- Transport & logistics --------------------------------------------
    family("Transport & logistics",
           "route planning;manifest handling;hours and rest recording;"
           "condition reporting;delivery confirmation",
           "dispatch;customers;depots;regulators",
           {
        "Truck driver": ("load securing records;tachograph compliance", "loading bays"),
        "Delivery driver": ("route sequencing;proof of delivery capture", "customers"),
        "Courier": ("parcel scanning;exception reporting", "sorting hubs"),
        "Bus driver": ("timetable keeping;incident reporting", "passengers;control room"),
        "Taxi driver": ("fare recording;licensing compliance", "passengers;licensing"),
        "Train driver": ("route knowledge;signal compliance;incident reporting", "signallers"),
        "Train conductor": ("ticket inspection;dispatch procedure", "drivers;passengers"),
        "Signaller": ("movement authority;block working records", "drivers;control"),
        "Airline pilot": ("flight planning;technical log entries;weather assessment", "air traffic control;dispatch"),
        "Cabin crew": ("safety demonstration;incident reporting", "pilots;passengers"),
        "Air traffic controller": ("separation management;clearance issuing", "pilots;adjacent sectors"),
        "Flight dispatcher": ("load sheet preparation;fuel planning", "pilots;operations"),
        "Ship captain": ("passage planning;log keeping;port paperwork", "port authorities;crew"),
        "Deck officer": ("watch keeping;cargo documentation", "captain;pilots"),
        "Marine pilot": ("channel navigation;bridge communication", "captains;port control"),
        "Harbour master": ("berth allocation;movement authorisation", "shipping agents"),
        "Warehouse operative": ("pick and pack;stock counting;location keeping", "supervisors"),
        "Forklift operator": ("load handling records;equipment checks", "warehouse teams"),
        "Warehouse manager": ("stock accuracy;labour planning;safety compliance", "carriers;suppliers"),
        "Logistics coordinator": ("booking;exception management;carrier liaison", "carriers;customers"),
        "Supply chain analyst": ("demand forecasting;inventory modelling", "buyers;planners"),
        "Freight forwarder": ("customs documentation;multimodal booking", "customs;carriers"),
        "Customs broker": ("declaration filing;tariff classification", "customs;importers"),
        "Fleet manager": ("maintenance scheduling;compliance auditing", "workshops;drivers"),
        "Dispatcher": ("job allocation;live tracking;exception handling", "drivers;customers"),
        "Postal worker": ("sorting;walk sequencing;delivery recording", "depots"),
    })

    # ---- Hospitality, food & retail ---------------------------------------
    family("Hospitality, food & retail",
           "order taking;stock rotation;hygiene record keeping;till reconciliation;"
           "customer handling;allergen awareness",
           "customers;suppliers;shift managers;environmental health",
           {
        "Chef": ("menu costing;prep list writing;brigade direction", "suppliers"),
        "Head chef": ("menu design;gross margin management;rota building", "owners;suppliers"),
        "Sous chef": ("service coordination;section covering", "head chef"),
        "Pastry chef": ("recipe scaling;production scheduling", "front of house"),
        "Line cook": ("station preparation;ticket timing", "kitchen team"),
        "Kitchen porter": ("wash-up cycles;waste segregation", "kitchen team"),
        "Baker": ("dough scheduling;oven loading;yield tracking", "shop floor"),
        "Butcher": ("cutting specification;traceability records", "abattoirs;customers"),
        "Fishmonger": ("freshness assessment;species labelling", "markets"),
        "Barista": ("drink specification;grind calibration;waste logging", "customers"),
        "Bartender": ("cocktail specification;stock control;age verification", "customers"),
        "Sommelier": ("list curation;pairing notes;cellar records", "suppliers"),
        "Waiter": ("order accuracy;table turning;upselling", "kitchen;customers"),
        "Restaurant manager": ("covers forecasting;rota building;complaint handling", "owners;suppliers"),
        "Hotel receptionist": ("reservation handling;check-in;billing", "guests;housekeeping"),
        "Hotel manager": ("occupancy management;rate setting;standards auditing", "owners;OTAs"),
        "Concierge": ("booking on behalf;local knowledge keeping", "guests;venues"),
        "Housekeeper": ("room status reporting;linen control", "reception;maintenance"),
        "Event coordinator": ("run sheet writing;supplier booking;on-the-day coordination", "clients;venues"),
        "Catering manager": ("menu planning;portion costing;dietary handling", "clients"),
        "Retail assistant": ("shelf replenishment;transaction handling;returns", "customers"),
        "Store manager": ("shrinkage control;rota building;sales targeting", "head office"),
        "Visual merchandiser": ("planogram execution;display building", "buyers;stores"),
        "Buyer": ("range planning;supplier negotiation;margin management", "suppliers"),
        "Merchandiser": ("allocation planning;stock intake forecasting", "buyers;stores"),
        "Stock controller": ("cycle counting;discrepancy investigation", "warehouse"),
        "Cashier": ("payment processing;float handling", "customers"),
        "Personal shopper": ("preference profiling;selection curation", "clients"),
        "Florist": ("arrangement design;perishable stock rotation", "growers;customers"),
        "Pharmacy technician": ("dispensing support;stock control", "pharmacists"),
    })

    # ---- Media, creative & communications ---------------------------------
    family("Media, creative & communications",
           "brief interpretation;draft production;revision handling;rights checking;"
           "deadline management;asset filing",
           "clients or editors;collaborators;legal;audiences",
           {
        "Journalist": ("source verification;interview conducting;copy filing", "editors;sources"),
        "News editor": ("commissioning;headline writing;fact checking", "reporters;legal"),
        "Sub-editor": ("copy editing;house style enforcement;layout fitting", "writers"),
        "Copywriter": ("headline and body writing;tone matching", "designers;clients"),
        "Content writer": ("keyword-aware drafting;series planning", "marketing"),
        "Technical author": ("procedure writing;screenshot capture;version tracking", "engineers"),
        "Editor": ("structural editing;author liaison;schedule keeping", "authors;production"),
        "Proofreader": ("error catching;consistency checking", "editors"),
        "Translator": ("meaning-preserving translation;terminology management", "clients;reviewers"),
        "Interpreter": ("live rendering;register matching;confidentiality", "speakers;audiences"),
        "Photographer": ("shot listing;lighting setup;retouch briefing", "clients;subjects"),
        "Photo editor": ("selection;colour grading;rights clearance", "photographers"),
        "Videographer": ("shot planning;audio capture;file management", "clients;editors"),
        "Video editor": ("assembly;colour;sound mixing;delivery specification", "directors"),
        "Motion designer": ("storyboarding;animation;render management", "creative directors"),
        "Sound engineer": ("recording;mixing;mastering;session filing", "artists;producers"),
        "Podcast producer": ("episode planning;guest booking;edit direction", "hosts;guests"),
        "Radio presenter": ("running order;live linking;caller handling", "producers;listeners"),
        "Broadcast producer": ("schedule building;compliance checking", "presenters;legal"),
        "Graphic designer": ("layout;typesetting;artwork preparation", "printers;clients"),
        "Brand designer": ("identity systems;guideline writing", "marketing"),
        "UX designer": ("flow mapping;prototype building;usability testing", "engineers;research"),
        "UI designer": ("component design;design token upkeep", "engineers"),
        "Illustrator": ("concept sketching;final artwork;licence terms", "art directors"),
        "Animator": ("keyframing;rig use;shot delivery", "directors"),
        "3D artist": ("modelling;texturing;scene assembly", "art directors"),
        "Art director": ("visual direction;critique;asset approval", "designers;clients"),
        "Creative director": ("concept ownership;pitch leading", "clients;teams"),
        "Social media manager": ("calendar planning;community replies;performance reporting", "audiences;legal"),
        "Community manager": ("moderation;escalation;sentiment reporting", "users;product"),
        "Public relations officer": ("release drafting;media list building;statement handling", "journalists"),
        "Communications manager": ("message discipline;spokesperson briefing", "leadership;press"),
        "Marketing manager": ("campaign planning;budget owning;channel mix", "agencies"),
        "Digital marketer": ("campaign setup;audience building;attribution reading", "platforms"),
        "SEO specialist": ("technical auditing;content gap analysis", "writers;engineers"),
        "Media buyer": ("inventory purchasing;pacing;placement verification", "publishers"),
        "Market researcher": ("survey design;panel management;finding write-up", "clients"),
        "Author": ("manuscript drafting;structural revision", "editors;agents"),
        "Screenwriter": ("outline;draft;notes incorporation", "producers;directors"),
        "Musician": ("session preparation;take delivery;rights registration", "producers;venues"),
        "Composer": ("cue writing;stem delivery;sync clearance", "directors;publishers"),
        "DJ": ("set building;beat matching;crowd reading", "venues;promoters"),
        "Actor": ("script learning;character notes;take delivery", "directors;agents"),
        "Voice actor": ("script marking;take consistency;booth workflow", "directors;studios"),
        "Presenter": ("autocue reading;interview conducting", "producers"),
        "Stage manager": ("cue calling;rehearsal scheduling;company management", "cast;crew"),
        "Lighting technician": ("rig planning;cue programming", "designers"),
        "Costume designer": ("sketching;fitting records;continuity", "wardrobe;actors"),
        "Set designer": ("model making;construction drawings", "carpenters"),
        "Casting director": ("brief interpretation;audition scheduling;shortlist building", "agents;producers"),
        "Film producer": ("budget owning;schedule building;deliverable tracking", "financiers;crew"),
        "Film director": ("shot listing;performance direction;edit supervision", "crew;cast"),
        "Games designer": ("mechanic specification;level design;balance tuning", "engineers;artists"),
        "Esports coach": ("scrim planning;VOD review;strategy sheets", "players;analysts"),
    })

    # ---- Public safety, defence & security --------------------------------
    family("Public safety, defence & security",
           "incident logging;evidence handling;chain-of-custody keeping;"
           "statement writing;protocol adherence",
           "control room;colleagues;public;courts",
           {
        "Police officer": ("scene preservation;arrest recording;statement taking", "prosecutors"),
        "Detective": ("investigation planning;disclosure preparation", "forensics;courts"),
        "Forensic scientist": ("sample analysis;expert report writing", "police;courts"),
        "Crime scene investigator": ("photography;exhibit packaging;log keeping", "detectives"),
        "Firefighter": ("incident command support;equipment checks;fire report writing", "control;ambulance"),
        "Fire investigator": ("origin determination;report writing", "insurers;police"),
        "Emergency dispatcher": ("call triage;resource allocation;record keeping", "responders;callers"),
        "Coastguard officer": ("search coordination;vessel tasking", "vessels;lifeboats"),
        "Lifeguard": ("surveillance;rescue recording", "supervisors"),
        "Security guard": ("patrol logging;access control;incident reporting", "clients;police"),
        "Door supervisor": ("age checking;refusal logging;conflict de-escalation", "venues;police"),
        "CCTV operator": ("monitoring;evidence export;incident logging", "security;police"),
        "Close protection officer": ("route planning;risk briefing", "principals"),
        "Prison officer": ("roll checking;incident reporting;搜 searching records", "governors;healthcare"),
        "Border officer": ("document examination;interview recording", "carriers;travellers"),
        "Customs officer": ("declaration checking;seizure recording", "importers"),
        "Military officer": ("orders writing;mission planning;after-action reporting", "command;units"),
        "Soldier": ("equipment accounting;patrol reporting", "section commanders"),
        "Intelligence analyst": ("source assessment;product writing;dissemination control", "collectors;consumers"),
        "Logistics officer": ("supply forecasting;movement scheduling", "depots;units"),
        "Emergency planner": ("scenario writing;exercise running;plan maintenance", "agencies"),
        "Environmental health officer": ("inspection;enforcement notice writing", "businesses;public"),
    })

    # ---- Agriculture, environment & animals -------------------------------
    family("Agriculture, environment & animals",
           "field or site record keeping;seasonal planning;compliance recording;"
           "condition monitoring;yield or population tracking",
           "landowners;regulators;buyers;veterinary or agronomy advisers",
           {
        "Farmer": ("crop rotation planning;input scheduling;subsidy paperwork", "merchants"),
        "Farm manager": ("labour planning;machinery scheduling;margin tracking", "owners"),
        "Agronomist": ("soil analysis interpretation;treatment recommendation", "farmers"),
        "Horticulturist": ("propagation scheduling;pest management records", "nurseries"),
        "Viticulturist": ("canopy management;harvest timing", "winemakers"),
        "Winemaker": ("fermentation logging;blending decisions", "growers;distributors"),
        "Beekeeper": ("hive inspection records;disease reporting", "regulators"),
        "Livestock farmer": ("herd records;movement reporting;welfare logging", "vets;abattoirs"),
        "Dairy farmer": ("yield recording;milk quality tracking", "processors"),
        "Poultry farmer": ("flock records;biosecurity logging", "processors;vets"),
        "Fisher": ("catch recording;quota compliance", "port authorities;buyers"),
        "Aquaculture technician": ("stock monitoring;feed recording;water quality logging", "vets;buyers"),
        "Forester": ("stand inventory;felling planning;restocking records", "regulators;mills"),
        "Ranger": ("visitor management;habitat recording;incident logging", "public;conservation bodies"),
        "Ecologist": ("survey design;species recording;impact assessment", "developers;regulators"),
        "Conservation officer": ("designation management;consent handling", "landowners"),
        "Environmental scientist": ("sampling;data interpretation;report writing", "regulators;clients"),
        "Climate analyst": ("emissions accounting;scenario modelling", "leadership;auditors"),
        "Sustainability manager": ("footprint reporting;target tracking;supplier engagement", "auditors;suppliers"),
        "Waste manager": ("duty of care records;route optimisation", "regulators;contractors"),
        "Recycling operative": ("stream separation;contamination reporting", "supervisors"),
        "Water treatment operator": ("dosing records;sample scheduling", "regulators;laboratory"),
        "Veterinary nurse": ("anaesthetic monitoring records;client instruction", "vets;owners"),
        "Animal care assistant": ("feeding records;behaviour noting", "vets;owners"),
        "Zookeeper": ("enrichment planning;husbandry records", "curators;vets"),
        "Dog trainer": ("session planning;progress recording", "owners"),
        "Groomer": ("coat assessment;appointment scheduling", "owners"),
        "Stable hand": ("feed and turnout records;tack maintenance", "owners;vets"),
        "Farrier": ("hoof assessment;shoeing records", "owners;vets"),
    })

    # ---- Energy, utilities & resources ------------------------------------
    family("Energy, utilities & resources",
           "asset record keeping;permit-to-work handling;outage reporting;"
           "meter and reading records;safety case compliance",
           "control room;regulators;field crews;customers",
           {
        "Power plant operator": ("load following;alarm response;shift handover writing", "grid operator"),
        "Grid controller": ("dispatch balancing;constraint management", "generators;traders"),
        "Energy trader": ("position management;forecast reading", "grid;counterparties"),
        "Utilities engineer": ("network modelling;reinforcement planning", "councils"),
        "Meter reader": ("reading capture;access exception reporting", "customers"),
        "Gas network technician": ("leak survey;emergency response records", "emergency services"),
        "Nuclear technician": ("dose recording;procedure compliance;surveillance testing", "regulators;health physics"),
        "Drilling engineer": ("well programme;daily drilling reports", "rig crews"),
        "Geologist": ("core logging;prospect mapping", "drillers;planners"),
        "Geophysicist": ("survey interpretation;model building", "explorers"),
        "Mine surveyor": ("void surveying;volume reporting", "mine planners"),
        "Pipeline technician": ("integrity inspection records;valve operation logs", "control room"),
        "Renewables project manager": ("consenting tracking;grid connection management", "councils;grid"),
    })

    # ---- Creator economy & online media ------------------------------------
    # Platform-native work. The skills here are the ones the platform
    # actually demands of the person holding the account — policy reading,
    # rights clearance, payout reconciliation, age and consent records —
    # not the performance itself, which is not a digital skill.
    family("Creator economy & online media",
           "content calendar keeping;platform policy reading;community "
           "moderation;analytics reading;rights and licence clearance;"
           "payout reconciliation;brand disclosure compliance",
           "platform support;payment processor;audience;brand partners;"
           "talent manager",
           {
        "Social media influencer": ("campaign brief reading;engagement reporting", "brand partners;agencies"),
        "Content creator": ("format testing;publishing schedule keeping", "platforms;editors"),
        "Video creator": ("shot list building;caption and thumbnail writing", "editors"),
        "Short-form video creator": ("hook testing;trend tracking", "platforms"),
        "Live streamer": ("stream scheduling;chat moderation;overlay operation", "moderators;subscribers"),
        "Podcast host": ("episode planning;guest booking;show note writing", "guests;distributors"),
        "Streamer moderator": ("rule enforcement;ban record keeping", "streamer;platform trust and safety"),
        "Digital content strategist": ("audience research;format planning;performance review", "marketing"),
        "Influencer marketing specialist": ("creator sourcing;deliverable tracking;disclosure checking", "creators;brands"),
        "Creator talent agent": ("rate carding;contract negotiation;deliverable chasing", "brands;creators"),
        "Creator manager": ("calendar ownership;inbox triage;payout tracking", "creators;platforms"),
        "Influencer agency owner": ("roster management;client reporting;P&L ownership", "brands;creators"),
        "Monetisation specialist": ("payout modelling;tier design;refund handling", "payment processor;platform"),
        "Creator economy coach": ("goal setting;channel audit;growth plan writing", "creators"),
        "Meme creator": ("format sourcing;attribution checking", "audience"),
        "Live commerce streamer": ("product script writing;stock checking;order handling", "merchants;fulfilment"),
        "Virtual influencer operator": ("persona continuity keeping;render pipeline operation;disclosure labelling", "studios;platforms"),
        "AI content creator": ("prompt and model record keeping;output review;provenance labelling", "platforms;rights holders"),
        "ASMR creator": ("audio capture;levels checking;release scheduling", "audience"),
        "Cosplay creator": ("build documentation;convention scheduling;rights checking", "conventions;rights holders"),
        "Erotic audio creator": ("age-gating compliance;release scheduling;consent record keeping", "platforms;payment processor"),
        "Erotic fiction writer": ("manuscript delivery;rights and licence tracking;age-gating compliance", "publishers;platforms"),
        "Adult content creator": ("age and consent record keeping;platform policy compliance;payout reconciliation;takedown handling", "platform trust and safety;payment processor"),
        "Adult platform performer": ("booking and release paperwork;age verification records;schedule keeping", "studios;platforms"),
        "Webcam performer": ("session scheduling;chat moderation;payout tracking", "platform support;payment processor"),
        "Webcam studio manager": ("performer onboarding;shift rota building;compliance record keeping", "performers;platforms"),
        "Adult film director": ("call sheet building;consent and release collection;post schedule keeping", "crew;performers"),
        "Adult film producer": ("budget tracking;rights clearance;distribution scheduling", "distributors;financiers"),
        "Adult content photographer": ("shoot planning;release form collection;asset delivery", "performers;platforms"),
        "Adult content videographer": ("shot planning;release form collection;footage handover", "editors;performers"),
        "Adult post-production editor": ("edit assembly;metadata tagging;delivery spec compliance", "producers;platforms"),
        "Adult industry talent agent": ("booking;rate negotiation;paperwork chasing", "studios;performers"),
        "Adult industry publicist": ("press scheduling;statement drafting;platform liaison", "press;platforms"),
        "Fetish model": ("booking paperwork;release form keeping;portfolio management", "photographers;platforms"),
        "Nude model": ("release form keeping;booking scheduling;portfolio management", "photographers;agencies"),
        "Burlesque performer": ("booking scheduling;set list keeping;venue liaison", "venues;promoters"),
        "Exotic dancer": ("shift scheduling;earnings recording;venue compliance", "venues"),
        "Adult platform moderator": ("policy application;report queue handling;escalation writing", "trust and safety;legal"),
        "Age verification specialist": ("verification workflow operation;audit trail keeping;exception handling", "platforms;regulators"),
        "Adult industry compliance officer": ("record-keeping audits;jurisdiction rule tracking;takedown response", "regulators;legal;platforms"),
        "Sex educator (online)": ("curriculum writing;source citation;platform policy compliance", "platforms;clinicians"),
        "Product reviewer (adult retail)": ("test protocol keeping;disclosure writing;affiliate record keeping", "retailers;audience"),
        "Adult entertainment booking agent": ("calendar management;contract issuing;travel booking", "venues;performers"),
    })

    # ---- Business, people & operations -------------------------------------
    family("Business, people & operations",
           "meeting minutes;process documentation;stakeholder updating;"
           "diary and deadline management;record retention",
           "colleagues;leadership;suppliers;customers",
           {
        "Chief executive": ("strategy setting;board reporting;capital allocation", "board;investors"),
        "Chief operating officer": ("operating cadence;cross-function unblocking", "function heads"),
        "Chief technology officer": ("technical strategy;build-or-buy decisions", "engineering;board"),
        "Chief information security officer": ("risk posture ownership;incident accountability", "board;regulators"),
        "General manager": ("P&L ownership;site operations", "head office"),
        "Operations manager": ("throughput management;SLA tracking;escalation handling", "teams;customers"),
        "Business analyst": ("requirement elicitation;process mapping;acceptance criteria", "stakeholders;developers"),
        "Management consultant": ("diagnostic;option appraisal;recommendation writing", "clients"),
        "Project manager": ("plan building;risk logging;status reporting", "sponsors;teams"),
        "Programme manager": ("dependency management;benefit tracking", "sponsors"),
        "Portfolio manager (projects)": ("prioritisation;resource balancing", "executives"),
        "Change manager": ("impact assessment;communication planning;adoption tracking", "affected teams"),
        "Human resources manager": ("policy maintenance;case handling;headcount planning", "managers;staff"),
        "Recruiter": ("role scoping;pipeline building;interview scheduling", "hiring managers;candidates"),
        "Talent acquisition specialist": ("sourcing;employer branding;offer management", "candidates"),
        "Learning and development manager": ("needs analysis;programme building;completion tracking", "managers"),
        "Compensation analyst": ("benchmarking;band modelling", "finance;HR"),
        "Employee relations specialist": ("grievance handling;investigation writing", "unions;managers"),
        "Office manager": ("facilities coordination;supplier management;onboarding logistics", "staff;landlords"),
        "Executive assistant": ("diary ownership;travel booking;gatekeeping", "executives"),
        "Administrator": ("data entry;filing;correspondence", "colleagues"),
        "Receptionist": ("visitor handling;call routing;post distribution", "visitors;staff"),
        "Customer service representative": ("case handling;knowledge base use;escalation", "customers"),
        "Customer success manager": ("onboarding;health scoring;renewal preparation", "customers;product"),
        "Account manager": ("relationship keeping;upsell planning;issue chasing", "clients"),
        "Sales representative": ("prospecting;pipeline hygiene;proposal writing", "prospects"),
        "Sales engineer": ("technical demonstration;requirement fit assessment", "prospects;engineering"),
        "Business development manager": ("partner scouting;deal structuring", "partners;legal"),
        "Bid manager": ("tender assembly;compliance matrix;submission control", "clients;subject experts"),
        "Facilities manager": ("maintenance scheduling;contractor management;compliance records", "contractors"),
        "Cleaner": ("area schedules;consumables recording", "facilities"),
        "Estate agent": ("valuation;viewing coordination;offer handling", "buyers;sellers;solicitors"),
        "Property manager": ("tenancy administration;maintenance dispatch;arrears chasing", "tenants;landlords"),
        "Letting agent": ("referencing;inventory recording;deposit handling", "tenants;landlords"),
        "Travel agent": ("itinerary building;booking;change handling", "operators;travellers"),
        "Tour guide": ("route commentary;group management", "visitors;venues"),
        "Fitness instructor": ("session planning;progression tracking", "members"),
        "Personal trainer": ("assessment;programme writing;adherence tracking", "clients"),
        "Sports coach": ("training planning;performance review;selection", "athletes;officials"),
        "Physio-sport therapist": ("injury assessment;return-to-play planning", "coaches;doctors"),
        "Nutritionist": ("intake assessment;plan writing", "clients;doctors"),
        "Hairdresser": ("consultation recording;colour formulation", "clients;suppliers"),
        "Barber": ("consultation;appointment management", "clients"),
        "Beautician": ("treatment recording;patch test logging", "clients"),
        "Massage therapist": ("intake screening;session notes", "clients;physios"),
        "Tattoo artist": ("design proofing;aftercare instruction;consent records", "clients;health inspectors"),
        "Funeral director": ("arrangement recording;statutory paperwork;family liaison", "registrars;families"),
        "Chaplain": ("pastoral visit notes;service preparation", "families;institutions"),
        "Religious minister": ("service leading;pastoral records;ceremony administration", "congregation"),
        "Charity fundraiser": ("donor recording;campaign tracking;grant applications", "donors;funders"),
        "Volunteer coordinator": ("rota building;induction;recognition tracking", "volunteers"),
        "Union representative": ("case support;consultation attendance", "members;employers"),
    })
