"""Regenerate the starter-collection gallery in README.md.

The gallery used to be 34 hand-written `<td>` blocks. Two things went wrong
with that, and both are the reason this file exists.

**It drifted from the seed list.** The starters live in `qrme/seed.py`; the
gallery was a second copy of their names maintained by hand, so a starter could
be added, renamed, or regrounded without the page showing it.

**It was five columns wide.** Five 118px portraits is roughly 590px of content,
and a phone gives about 390. On GitHub's mobile view the fourth column was
sliced mid-word and the fifth was gone entirely — every profile past the third
was unreachable to anybody reading on a phone, which is most people. Three
columns fit. That is the whole reason for the number.

**And it showed a name and an industry.** A profile's own front page (screen 5)
carries an avatar bubble, a role, stat tiles and a Chat button. The gallery
showed a portrait with two lines of caption under it, so the starters looked
thinner on the page than they are in the product. Each cell is now the card
itself, generated by `tools/starter_cards.py` — run that first, this second.

Roles are curated here rather than extracted from the bios. A regex over "A
warm, plain-spoken physician and health educator with twenty years…" produces
something almost right, and almost right in 34 places is worse than a list
somebody read once. Each line below is the credential its bio opens with,
shortened. `check()` fails if a starter has no role, so adding one to
`seed.py` without a line here is a build error rather than a blank cell.

    python3 tools/starter_gallery.py           # rewrite README.md in place
    python3 tools/starter_gallery.py --check   # verify, exit 1 on drift
"""

from __future__ import annotations

import ast
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
SEED = ROOT / "qrme" / "seed.py"

# Two, because each cell is now a whole Profile Home card rather than a
# thumbnail. Cards are authored 352 wide and shown at 176, so two of them plus
# the table's padding sit inside a 390px phone with room to spare. Three would
# clip again, which is the defect this file was written to end.
COLUMNS = 2
THUMB = 176

BEGIN = "<!-- starter-gallery:begin -->"
END = "<!-- starter-gallery:end -->"

# handle -> the credential its bio opens with, shortened to fit a cell.
# Lower case, because that is how the app's own profile header writes a role
# (screen 5 reads "retired fee-only financial planner"), and the gallery
# exists to look like the product rather than like a directory listing.
ROLES: dict[str, str] = {
    "dr_amara_osei": "physician &amp; health educator",
    "marcus_bell": "retired fee-only financial planner",
    "priya_raman": "software architect",
    "elena_vasquez": "classroom teacher &amp; learning coach",
    "jonathan_ashe": "retired contracts attorney",
    "sam_whitfield": "row-crop &amp; vegetable farmer",
    "ingrid_halvorsen": "plant operations engineer",
    "diego_fuentes": "general contractor",
    "naomi_clarke": "residential broker",
    "tomas_rivera": "power-systems engineer",
    "odessa_grant": "logistics director",
    "ken_nakamura": "omnichannel merchant",
    "lucia_moretti": "hotelier",
    "ray_coleman": "documentary producer",
    "wren_okafor": "designer-illustrator",
    "coach_dana_reyes": "strength &amp; conditioning coach",
    "chef_henri_laurent": "classically trained chef",
    "dr_sana_iqbal": "climate scientist",
    "pete_kowalski": "retired city administrator",
    "grace_mwangi": "nonprofit director",
    "dr_felix_baum": "research physicist",
    "aisha_diallo": "network engineer",
    "harold_jenkins": "claims adjuster &amp; underwriter",
    "rosa_delgado": "master mechanic",
    "cmdr_ellen_park": "aerospace engineer &amp; test pilot",
    "mimi_beaumont": "stylist &amp; atelier seamstress",
    "jack_osei_turner": "brand strategist",
    "nadia_petrova": "defensive security analyst",
    "bev_lindqvist": "HR director",
    "otis_marsh": "session musician &amp; teacher",
    "dr_lena_whitcomb": "clinical psychologist",
    "dr_marcus_adeyemi": "psychiatrist",
    "dr_priya_nair": "family &amp; couples therapist",
    "vivienne_sable": "cabaret headliner &amp; burlesque historian",
}


def starters() -> list[tuple[str, str, str, list[str]]]:
    """(handle, industry, display name, tags) for every seeded starter.

    Read out of `seed.py` by parsing the literal rather than importing it,
    so generating a page never touches a database or needs the package's
    dependencies installed.
    """
    src = SEED.read_text()
    out: list[tuple[str, str, str, list[str]]] = []
    for name in ("STARTERS", "RATED"):
        m = re.search(rf"^{name}\s*[:=][^=]*=\s*\[", src, re.M)
        if m is None:
            continue
        i = src.index("[", m.end() - 1)
        depth = 0
        for j in range(i, len(src)):
            if src[j] == "[":
                depth += 1
            elif src[j] == "]":
                depth -= 1
                if depth == 0:
                    break
        for row in ast.literal_eval(src[i:j + 1]):
            handle, industry, display, _kind, tags, *_ = row
            out.append((handle, industry, display, list(tags)))
    return out


def cell(handle: str, industry: str, display: str, tags: list[str]) -> str:
    """One card. The caption lives inside the SVG, not under it.

    The old cell put a name, a role and a tag list in `<sub>` beneath a
    portrait, which is a caption pretending to be a profile. The card carries
    all of it — bubble, name, role, industry, stat tiles, Chat — so the only
    thing left out here is the alt text, which has to stay outside the image
    for anybody reading with a screen reader.
    """
    role = ROLES[handle].replace("&amp;", "&")
    return (
        f'    <td align="center" width="50%" valign="top">'
        f'<img src="docs/portraits/cards/{handle}.svg" width="{THUMB}" '
        f'alt="{display} — {role}, {industry.replace("_", " ")}"></td>'
    )


def table() -> str:
    rows = starters()
    missing = [h for h, *_ in rows if h not in ROLES]
    if missing:
        raise SystemExit(
            "starters with no role line in tools/starter_gallery.py: "
            + ", ".join(missing))
    out = ["<table>"]
    for i in range(0, len(rows), COLUMNS):
        out.append("  <tr>")
        out += [cell(*r) for r in rows[i:i + COLUMNS]]
        out.append("  </tr>")
    out.append("</table>")
    return "\n".join(out)


def main() -> int:
    check = "--check" in sys.argv
    text = README.read_text()
    if BEGIN not in text or END not in text:
        raise SystemExit(f"README.md is missing {BEGIN} / {END} markers")
    head, rest = text.split(BEGIN, 1)
    _old, tail = rest.split(END, 1)
    new = f"{head}{BEGIN}\n{table()}\n{END}{tail}"
    if new == text:
        print("starter gallery is up to date")
        return 0
    if check:
        print("starter gallery is stale — run tools/starter_gallery.py")
        return 1
    README.write_text(new)
    print(f"rewrote the starter gallery: {len(starters())} profiles, "
          f"{COLUMNS} columns")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
