package app.qrme.studio

import android.content.res.Resources

/**
 * App-chrome localization: tab names, screen titles, and the most common
 * actions, in every language the backend supports. Content (chat, guidance,
 * persona text) is localized server-side by the profile's language setting;
 * this table covers the frame around it. Missing keys fall back to English.
 */
object L10n {
    fun t(key: String, lang: String): String =
        table[key]?.let { it[lang] ?: it["en"] } ?: key


    /** A translated sentence with its `{placeholders}` filled in.
     *
     * The console's rows carry `{id}`, `{now}`, `{matched}` and friends, and
     * the shells took the same rows — so they need the same substitution.
     * Building the sentence by concatenation instead is how a translation
     * ends up in English word order in nine languages.
     */
    fun fill(key: String, lang: String, values: Map<String, String>): String {
        var out = t(key, lang)
        for ((name, value) in values) out = out.replace("{$name}", value)
        return out
    }

    val supported = listOf("en", "es", "fr", "de", "pt", "it", "ja", "zh",
                           "hi", "ar")

    /**
     * The language of somebody who has no profile to take one from.
     *
     * `AppState.language` comes from the profile's stored setting and is
     * "en" until one exists — right for the tab bar, useless for the
     * without-an-account screen, which exists for a person who has no
     * profile and is not going to make one. Their phone has been carrying
     * the answer in the system configuration all along.
     *
     * Region dropped; anything this app does not carry falls back to English
     * rather than guessing.
     */
    fun deviceLanguage(): String {
        val locales = Resources.getSystem().configuration.locales
        for (i in 0 until locales.size()) {
            val base = locales[i].language.lowercase()
            if (supported.contains(base)) return base
        }
        return "en"
    }

    private val table: Map<String, Map<String, String>> = mapOf(
        "corner.title" to mapOf("en" to "Your corner", "es" to "Tu rincón", "fr" to "Votre coin", "de" to "Deine Ecke", "pt" to "O seu cantinho", "it" to "Il tuo angolo", "ja" to "あなたのコーナー", "zh" to "你的角落", "hi" to "आपका कोना", "ar" to "ركنك"),
        "corner.walls" to mapOf("en" to "Hex colors, http(s) links, plain text, real friends — the sandbox walls.", "es" to "Colores hex, enlaces http(s), texto plano, amigos reales — los muros del sandbox.", "fr" to "Couleurs hex, liens http(s), texte brut, vrais amis — les murs du bac à sable.", "de" to "Hex-Farben, http(s)-Links, Klartext, echte Freunde — die Wände der Sandbox.", "pt" to "Cores hex, links http(s), texto simples, amigos reais — as paredes da sandbox.", "it" to "Colori hex, link http(s), testo semplice, amici veri — i muri della sandbox.", "ja" to "16進カラー、http(s) リンク、プレーンテキスト、実際の友だち — サンドボックスの壁。", "zh" to "十六进制颜色、http(s) 链接、纯文本、真实好友 — 沙盒之墙。", "hi" to "हेक्स रंग, http(s) लिंक, सादा पाठ, असली दोस्त — सैंडबॉक्स की दीवारें।", "ar" to "ألوان سداسية وروابط http(s) ونص عادي وأصدقاء حقيقيون — جدران الصندوق الرملي."),
        "corner.headline" to mapOf("en" to "Headline", "es" to "Titular", "fr" to "Accroche", "de" to "Überschrift", "pt" to "Título", "it" to "Titolo", "ja" to "見出し", "zh" to "标题", "hi" to "शीर्षक", "ar" to "العنوان"),
        "corner.about" to mapOf("en" to "About you", "es" to "Sobre ti", "fr" to "À propos de vous", "de" to "Über dich", "pt" to "Sobre si", "it" to "Su di te", "ja" to "自己紹介", "zh" to "关于你", "hi" to "आपके बारे में", "ar" to "عنك"),
        "corner.bg" to mapOf("en" to "Background color", "es" to "Color de fondo", "fr" to "Couleur de fond", "de" to "Hintergrundfarbe", "pt" to "Cor de fundo", "it" to "Colore di sfondo", "ja" to "背景色", "zh" to "背景色", "hi" to "पृष्ठभूमि रंग", "ar" to "لون الخلفية"),
        "corner.accent" to mapOf("en" to "Accent color", "es" to "Color de acento", "fr" to "Couleur d'accent", "de" to "Akzentfarbe", "pt" to "Cor de destaque", "it" to "Colore d'accento", "ja" to "アクセント色", "zh" to "强调色", "hi" to "मुख्य रंग", "ar" to "لون التمييز"),
        "corner.save" to mapOf("en" to "Save the page", "es" to "Guardar la página", "fr" to "Enregistrer la page", "de" to "Seite speichern", "pt" to "Guardar a página", "it" to "Salva la pagina", "ja" to "ページを保存", "zh" to "保存页面", "hi" to "पृष्ठ सहेजें", "ar" to "احفظ الصفحة"),
        "corner.switches" to mapOf("en" to "Your switches", "es" to "Tus interruptores", "fr" to "Vos interrupteurs", "de" to "Deine Schalter", "pt" to "Os seus interruptores", "it" to "I tuoi interruttori", "ja" to "あなたのスイッチ", "zh" to "你的开关", "hi" to "आपके स्विच", "ar" to "مفاتيحك"),
        "corner.switch.messaging" to mapOf("en" to "Messaging", "es" to "Mensajería", "fr" to "Messagerie", "de" to "Nachrichten", "pt" to "Mensagens", "it" to "Messaggi", "ja" to "メッセージ", "zh" to "消息", "hi" to "संदेश", "ar" to "المراسلة"),
        "corner.switch.homepage" to mapOf("en" to "Homepage is public", "es" to "Página personal pública", "fr" to "Page personnelle publique", "de" to "Startseite öffentlich", "pt" to "Página pessoal pública", "it" to "Pagina personale pubblica", "ja" to "ホームページを公開", "zh" to "主页公开", "hi" to "होमपेज सार्वजनिक", "ar" to "الصفحة عامة"),
        "corner.messages" to mapOf("en" to "Messages", "es" to "Mensajes", "fr" to "Messages", "de" to "Nachrichten", "pt" to "Mensagens", "it" to "Messaggi", "ja" to "メッセージ", "zh" to "消息", "hi" to "संदेश", "ar" to "الرسائل"),
        "corner.friends_only" to mapOf("en" to "Between friends only — the friendship is the consent record.", "es" to "Solo entre amigos — la amistad es el registro de consentimiento.", "fr" to "Entre amis seulement — l'amitié est le registre du consentement.", "de" to "Nur unter Freunden — die Freundschaft ist die Einwilligung.", "pt" to "Só entre amigos — a amizade é o registo de consentimento.", "it" to "Solo tra amici — l'amicizia è il registro del consenso.", "ja" to "友だち同士だけ — 友情が同意の記録です。", "zh" to "仅限好友之间 — 友谊即同意记录。", "hi" to "केवल दोस्तों के बीच — दोस्ती ही सहमति का रिकॉर्ड है।", "ar" to "بين الأصدقاء فقط — الصداقة هي سجل الموافقة."),
        "corner.open" to mapOf("en" to "Open", "es" to "Abrir", "fr" to "Ouvrir", "de" to "Öffnen", "pt" to "Abrir", "it" to "Apri", "ja" to "開く", "zh" to "打开", "hi" to "खोलें", "ar" to "افتح"),
        "corner.to" to mapOf("en" to "To (profile id)", "es" to "Para (id de perfil)", "fr" to "À (id de profil)", "de" to "An (Profil-ID)", "pt" to "Para (id de perfil)", "it" to "A (id profilo)", "ja" to "宛先（プロフィールID）", "zh" to "发给（档案 ID）", "hi" to "किसे (प्रोफ़ाइल आईडी)", "ar" to "إلى (معرّف الملف)"),
        "corner.send" to mapOf("en" to "Send", "es" to "Enviar", "fr" to "Envoyer", "de" to "Senden", "pt" to "Enviar", "it" to "Invia", "ja" to "送信", "zh" to "发送", "hi" to "भेजें", "ar" to "أرسل"),
        "shop.title" to mapOf("en" to "Shops", "es" to "Tiendas", "fr" to "Boutiques", "de" to "Läden", "pt" to "Lojas", "it" to "Negozi", "ja" to "ショップ", "zh" to "商店", "hi" to "दुकानें", "ar" to "المتاجر"),
        "shop.sub" to mapOf("en" to "Goods and services — not a desk, no sessions", "es" to "Bienes y servicios — no es un mostrador, sin sesiones", "fr" to "Biens et services — pas un comptoir, pas de sessions", "de" to "Waren und Dienstleistungen — kein Schalter, keine Sitzungen", "pt" to "Bens e serviços — não é um balcão, sem sessões", "it" to "Beni e servizi — non è un banco, niente sessioni", "ja" to "品物とサービス — カウンターではなく、セッションもなし", "zh" to "商品与服务 — 不是柜台，没有会话", "hi" to "सामान और सेवाएँ — डेस्क नहीं, कोई सत्र नहीं", "ar" to "سلع وخدمات — ليس مكتبًا ولا جلسات"),
        "shop.browse" to mapOf("en" to "Browse", "es" to "Ver", "fr" to "Parcourir", "de" to "Ansehen", "pt" to "Ver", "it" to "Sfoglia", "ja" to "見る", "zh" to "逛逛", "hi" to "देखें", "ar" to "تصفّح"),
        "shop.order" to mapOf("en" to "Order", "es" to "Pedir", "fr" to "Commander", "de" to "Bestellen", "pt" to "Encomendar", "it" to "Ordina", "ja" to "注文", "zh" to "下单", "hi" to "ऑर्डर करें", "ar" to "اطلب"),
        "shop.mine" to mapOf("en" to "Your orders", "es" to "Tus pedidos", "fr" to "Vos commandes", "de" to "Deine Bestellungen", "pt" to "Os seus pedidos", "it" to "I tuoi ordini", "ja" to "あなたの注文", "zh" to "你的订单", "hi" to "आपके ऑर्डर", "ar" to "طلباتك"),
        "shop.cancel" to mapOf("en" to "Cancel", "es" to "Cancelar", "fr" to "Annuler", "de" to "Stornieren", "pt" to "Cancelar", "it" to "Annulla", "ja" to "キャンセル", "zh" to "取消", "hi" to "रद्द करें", "ar" to "إلغاء"),
        "shop.till" to mapOf("en" to "Your till", "es" to "Tu caja", "fr" to "Votre caisse", "de" to "Deine Kasse", "pt" to "A sua caixa", "it" to "La tua cassa", "ja" to "あなたのレジ", "zh" to "你的收银台", "hi" to "आपका गल्ला", "ar" to "صندوقك"),
        "shop.till_note" to mapOf("en" to "One shop per profile. Fulfilment credits your ledger — simulated money, real accounting.", "es" to "Una tienda por perfil. Completar abona tu libro — dinero simulado, contabilidad real.", "fr" to "Une boutique par profil. L'exécution crédite votre registre — argent simulé, comptabilité réelle.", "de" to "Ein Laden pro Profil. Erfüllung schreibt deinem Buch gut — simuliertes Geld, echte Buchführung.", "pt" to "Uma loja por perfil. Concluir credita o seu livro — dinheiro simulado, contabilidade real.", "it" to "Un negozio per profilo. L'evasione accredita il tuo registro — denaro simulato, contabilità reale.", "ja" to "プロフィールごとに一軒。履行で台帳に記帳 — お金は擬似、記帳は本物。", "zh" to "每个档案一家店。履约记入账本 — 模拟货币，真实记账。", "hi" to "प्रति प्रोफ़ाइल एक दुकान। पूर्ति बहीखाते में जमा — नकली पैसा, असली हिसाब।", "ar" to "متجر واحد لكل ملف. الإنجاز يُقيّد في دفترك — مال محاكى ومحاسبة حقيقية."),
        "shop.name" to mapOf("en" to "Shop name", "es" to "Nombre de la tienda", "fr" to "Nom de la boutique", "de" to "Ladenname", "pt" to "Nome da loja", "it" to "Nome del negozio", "ja" to "ショップ名", "zh" to "店铺名称", "hi" to "दुकान का नाम", "ar" to "اسم المتجر"),
        "shop.open" to mapOf("en" to "Open the shop", "es" to "Abrir la tienda", "fr" to "Ouvrir la boutique", "de" to "Laden eröffnen", "pt" to "Abrir a loja", "it" to "Apri il negozio", "ja" to "ショップを開く", "zh" to "开店", "hi" to "दुकान खोलें", "ar" to "افتح المتجر"),
        "shop.offer_title" to mapOf("en" to "Offering", "es" to "Artículo", "fr" to "Article", "de" to "Angebot", "pt" to "Artigo", "it" to "Articolo", "ja" to "商品", "zh" to "商品", "hi" to "पेशकश", "ar" to "المعروض"),
        "shop.price" to mapOf("en" to "Price", "es" to "Precio", "fr" to "Prix", "de" to "Preis", "pt" to "Preço", "it" to "Prezzo", "ja" to "価格", "zh" to "价格", "hi" to "क़ीमत", "ar" to "السعر"),
        "shop.add" to mapOf("en" to "Add", "es" to "Añadir", "fr" to "Ajouter", "de" to "Hinzufügen", "pt" to "Adicionar", "it" to "Aggiungi", "ja" to "追加", "zh" to "添加", "hi" to "जोड़ें", "ar" to "أضف"),
        "shop.retire" to mapOf("en" to "Retire", "es" to "Retirar", "fr" to "Retirer", "de" to "Zurückziehen", "pt" to "Retirar", "it" to "Ritira", "ja" to "取り下げる", "zh" to "下架", "hi" to "हटाएँ", "ar" to "اسحب"),
        "shop.book" to mapOf("en" to "Order book", "es" to "Libro de pedidos", "fr" to "Carnet de commandes", "de" to "Auftragsbuch", "pt" to "Livro de pedidos", "it" to "Registro ordini", "ja" to "受注一覧", "zh" to "订单簿", "hi" to "ऑर्डर बही", "ar" to "سجل الطلبات"),
        "shop.accept" to mapOf("en" to "Accept", "es" to "Aceptar", "fr" to "Accepter", "de" to "Annehmen", "pt" to "Aceitar", "it" to "Accetta", "ja" to "受ける", "zh" to "接受", "hi" to "स्वीकारें", "ar" to "اقبل"),
        "shop.fulfil" to mapOf("en" to "Fulfil", "es" to "Completar", "fr" to "Exécuter", "de" to "Erfüllen", "pt" to "Concluir", "it" to "Evadi", "ja" to "履行する", "zh" to "履约", "hi" to "पूर्ति करें", "ar" to "أنجز"),
        "desk.counter" to mapOf("en" to "Your side of the counter", "es" to "Tu lado del mostrador", "fr" to "Votre côté du comptoir", "de" to "Deine Seite des Tresens", "pt" to "O seu lado do balcão", "it" to "Il tuo lato del banco", "ja" to "あなた側のカウンター", "zh" to "你这一侧的柜台", "hi" to "काउंटर का आपका पक्ष", "ar" to "جانبك من المكتب"),
        "desk.counter.show" to mapOf("en" to "Show my sessions", "es" to "Mostrar mis sesiones", "fr" to "Afficher mes sessions", "de" to "Meine Sitzungen zeigen", "pt" to "Mostrar as minhas sessões", "it" to "Mostra le mie sessioni", "ja" to "自分のセッションを表示", "zh" to "显示我的会话", "hi" to "मेरे सत्र दिखाएँ", "ar" to "أظهر جلساتي"),
        "desk.counter.close_all" to mapOf("en" to "Close it all", "es" to "Cerrarlo todo", "fr" to "Tout fermer", "de" to "Alles schließen", "pt" to "Fechar tudo", "it" to "Chiudi tutto", "ja" to "すべて閉じる", "zh" to "全部关闭", "hi" to "सब बंद करें", "ar" to "أغلق كل شيء"),
        "desk.counter.connect" to mapOf("en" to "Connect it", "es" to "Conectarlo", "fr" to "Le connecter", "de" to "Verbinden", "pt" to "Ligar", "it" to "Connettilo", "ja" to "接続する", "zh" to "连接", "hi" to "जोड़ें", "ar" to "وصِّله"),
        "desk.counter.decline" to mapOf("en" to "No", "es" to "No", "fr" to "Non", "de" to "Nein", "pt" to "Não", "it" to "No", "ja" to "いいえ", "zh" to "不", "hi" to "नहीं", "ar" to "لا"),
        "desk.counter.end" to mapOf("en" to "End this link", "es" to "Terminar este enlace", "fr" to "Mettre fin à ce lien", "de" to "Diesen Link beenden", "pt" to "Terminar esta ligação", "it" to "Termina questo collegamento", "ja" to "このリンクを終了", "zh" to "终止此链接", "hi" to "यह लिंक समाप्त करें", "ar" to "أنهِ هذا الرابط"),
        "desk.counter.staff" to mapOf("en" to "Staff the counter", "es" to "Atender el mostrador", "fr" to "Tenir le comptoir", "de" to "Den Tresen besetzen", "pt" to "Atender o balcão", "it" to "Presidiare il banco", "ja" to "カウンターに立つ", "zh" to "值守柜台", "hi" to "काउंटर संभालें", "ar" to "قِف خلف المكتب"),
        "desk.counter.staff.token" to mapOf("en" to "Desk token", "es" to "Token del escritorio", "fr" to "Jeton du bureau", "de" to "Desk-Token", "pt" to "Token da banca", "it" to "Token della postazione", "ja" to "デスクトークン", "zh" to "展台令牌", "hi" to "डेस्क टोकन", "ar" to "رمز المكتب"),
        "desk.counter.staff.caller" to mapOf("en" to "Caller's interactor id", "es" to "Id de interactor de quien llama", "fr" to "Identifiant d'interacteur de l'appelant", "de" to "Interactor-ID des Anrufers", "pt" to "Id de interator de quem chama", "it" to "Id interactor di chi chiama", "ja" to "呼び出した人のインタラクターID", "zh" to "来访者的互动者 id", "hi" to "कॉल करने वाले की इंटरैक्टर आईडी", "ar" to "معرّف المتفاعل للمتصل"),
        "desk.counter.staff.open" to mapOf("en" to "Open a session", "es" to "Abrir una sesión", "fr" to "Ouvrir une session", "de" to "Sitzung öffnen", "pt" to "Abrir uma sessão", "it" to "Apri una sessione", "ja" to "セッションを開く", "zh" to "开启会话", "hi" to "सत्र खोलें", "ar" to "افتح جلسة"),
        "desk.counter.staff.target" to mapOf("en" to "What, by name", "es" to "Qué cosa, por su nombre", "fr" to "Quoi, par son nom", "de" to "Was, beim Namen", "pt" to "O quê, pelo nome", "it" to "Che cosa, per nome", "ja" to "何を（名前で）", "zh" to "连接什么（写明名称）", "hi" to "क्या, नाम से", "ar" to "ماذا، بالاسم"),
        "desk.counter.staff.scope" to mapOf("en" to "Scope, in words they will read", "es" to "Alcance, en palabras que la persona leerá", "fr" to "Périmètre, en mots qu'elle lira", "de" to "Umfang, in Worten, die die Person lesen wird", "pt" to "Âmbito, em palavras que a pessoa lerá", "it" to "Ambito, in parole che la persona leggerà", "ja" to "範囲。相手が読む言葉で", "zh" to "范围，用对方会读到的文字", "hi" to "दायरा, उन शब्दों में जो वह पढ़ेगा", "ar" to "النطاق، بكلمات سيقرؤها الشخص"),
        "desk.counter.staff.offer" to mapOf("en" to "Offer a screen share", "es" to "Ofrecer compartir pantalla", "fr" to "Proposer un partage d'écran", "de" to "Bildschirmfreigabe anbieten", "pt" to "Oferecer partilha de ecrã", "it" to "Offri una condivisione dello schermo", "ja" to "画面共有を提案する", "zh" to "发出屏幕共享邀请", "hi" to "स्क्रीन साझा करने की पेशकश करें", "ar" to "اعرض مشاركة الشاشة"),
        "obj.timeline.title" to mapOf("en" to "What has happened to your case", "es" to "Qué ha pasado con su caso", "fr" to "Ce qu'il est advenu de votre dossier", "de" to "Was mit Ihrem Fall geschehen ist", "pt" to "O que aconteceu ao seu caso", "it" to "Cosa è successo al tuo caso", "ja" to "あなたの案件の経過", "zh" to "你的案件进展如何", "hi" to "आपके मामले में क्या हुआ", "ar" to "ما جرى في قضيتك"),
        "obj.timeline.go" to mapOf("en" to "Show the record", "es" to "Ver el registro", "fr" to "Afficher le registre", "de" to "Akte anzeigen", "pt" to "Ver o registo", "it" to "Mostra il registro", "ja" to "記録を見る", "zh" to "查看记录", "hi" to "रिकॉर्ड दिखाएँ", "ar" to "أظهر السجل"),
        "obj.timeline.sealed" to mapOf("en" to "sealed in the vault", "es" to "sellado en la bóveda", "fr" to "scellé dans le coffre", "de" to "im Tresor versiegelt", "pt" to "selado no cofre", "it" to "sigillato nella cassaforte", "ja" to "保管庫に封印済み", "zh" to "已封存于保险库", "hi" to "वॉल्ट में सील किया गया", "ar" to "مختوم في الخزنة"),
        "obj.timeline.empty" to mapOf("en" to "Nothing on this case yet.", "es" to "Todavía nada en este caso.", "fr" to "Rien encore sur ce dossier.", "de" to "Zu diesem Fall noch nichts.", "pt" to "Ainda nada neste caso.", "it" to "Ancora nulla su questo caso.", "ja" to "この案件にはまだ何もありません。", "zh" to "此案件暂无记录。", "hi" to "इस मामले पर अभी कुछ नहीं।", "ar" to "لا شيء في هذه القضية بعد."),
        "obj.event.opened" to mapOf("en" to "opened", "es" to "abierta", "fr" to "ouverte", "de" to "eröffnet", "pt" to "aberta", "it" to "aperta", "ja" to "受理", "zh" to "已提出", "hi" to "खोला गया", "ar" to "فُتحت"),
        "obj.event.reattested" to mapOf("en" to "basis re-attested", "es" to "base reacreditada", "fr" to "base réattestée", "de" to "Grundlage erneut bestätigt", "pt" to "base reatestada", "it" to "base riattestata", "ja" to "根拠を再証明", "zh" to "已重新证明依据", "hi" to "आधार पुनः प्रमाणित", "ar" to "أُعيد إثبات الأساس"),
        "obj.event.upheld" to mapOf("en" to "upheld", "es" to "estimada", "fr" to "retenue", "de" to "stattgegeben", "pt" to "deferida", "it" to "accolta", "ja" to "認容", "zh" to "已支持", "hi" to "स्वीकृत", "ar" to "قُبلت"),
        "obj.event.dismissed" to mapOf("en" to "dismissed", "es" to "desestimada", "fr" to "rejetée", "de" to "abgewiesen", "pt" to "indeferida", "it" to "respinta", "ja" to "却下", "zh" to "已驳回", "hi" to "खारिज", "ar" to "رُفضت"),
        "obj.event.withdrawn" to mapOf("en" to "consent withdrawn", "es" to "consentimiento retirado", "fr" to "consentement retiré", "de" to "Einwilligung zurückgezogen", "pt" to "consentimento retirado", "it" to "consenso ritirato", "ja" to "同意の撤回", "zh" to "已撤回同意", "hi" to "सहमति वापस", "ar" to "سُحبت الموافقة"),
        "obj.event.revoked" to mapOf("en" to "authorization revoked", "es" to "autorización revocada", "fr" to "autorisation révoquée", "de" to "Autorisierung widerrufen", "pt" to "autorização revogada", "it" to "autorizzazione revocata", "ja" to "承認の取り消し", "zh" to "已撤销授权", "hi" to "प्राधिकरण रद्द", "ar" to "أُلغي التفويض"),
        "obj.event.terminated" to mapOf("en" to "profile terminated", "es" to "perfil terminado", "fr" to "profil supprimé", "de" to "Profil beendet", "pt" to "perfil terminado", "it" to "profilo terminato", "ja" to "プロフィール終了", "zh" to "资料已终止", "hi" to "प्रोफ़ाइल समाप्त", "ar" to "أُنهي الملف"),
        "obj.actor.objector" to mapOf("en" to "you", "es" to "usted", "fr" to "vous", "de" to "Sie", "pt" to "você", "it" to "tu", "ja" to "あなた", "zh" to "你", "hi" to "आप", "ar" to "أنت"),
        "obj.actor.owner" to mapOf("en" to "the owner", "es" to "el titular", "fr" to "le propriétaire", "de" to "die Inhaberin oder der Inhaber", "pt" to "o titular", "it" to "il titolare", "ja" to "所有者", "zh" to "所有者", "hi" to "स्वामी", "ar" to "المالك"),
        "obj.actor.reviewer" to mapOf("en" to "a reviewer", "es" to "un revisor", "fr" to "un examinateur", "de" to "eine prüfende Person", "pt" to "um revisor", "it" to "un revisore", "ja" to "審査担当", "zh" to "审核人", "hi" to "समीक्षक", "ar" to "مُراجِع"),
        "obj.actor.subject" to mapOf("en" to "the subject", "es" to "el sujeto", "fr" to "la personne concernée", "de" to "die betroffene Person", "pt" to "o titular dos dados", "it" to "la persona interessata", "ja" to "本人", "zh" to "当事人", "hi" to "संबंधित व्यक्ति", "ar" to "الشخص المعني"),
        "obj.actor.estate" to mapOf("en" to "the estate", "es" to "la sucesión", "fr" to "la succession", "de" to "der Nachlass", "pt" to "o espólio", "it" to "gli eredi", "ja" to "遺族", "zh" to "遗产代表", "hi" to "संपदा", "ar" to "الورثة"),
        "obj.actor.system" to mapOf("en" to "the platform", "es" to "la plataforma", "fr" to "la plateforme", "de" to "die Plattform", "pt" to "a plataforma", "it" to "la piattaforma", "ja" to "プラットフォーム", "zh" to "平台", "hi" to "प्लेटफ़ॉर्म", "ar" to "المنصة"),
        "tab.overview" to mapOf(
            "en" to "Overview", "es" to "Resumen", "fr" to "Aperçu",
            "de" to "Übersicht", "pt" to "Visão geral", "it" to "Panoramica",
            "ja" to "概要", "zh" to "概览", "hi" to "अवलोकन", "ar" to "نظرة عامة"),
        "tab.chat" to mapOf(
            "en" to "Chat", "es" to "Chat", "fr" to "Discussion",
            "de" to "Chat", "pt" to "Conversa", "it" to "Chat",
            "ja" to "チャット", "zh" to "聊天", "hi" to "चैट", "ar" to "محادثة"),
        "tab.studio" to mapOf(
            "en" to "Studio", "es" to "Estudio", "fr" to "Studio",
            "de" to "Studio", "pt" to "Estúdio", "it" to "Studio",
            "ja" to "スタジオ", "zh" to "工作室", "hi" to "स्टूडियो", "ar" to "الاستوديو"),
        "tab.connect" to mapOf(
            "en" to "Connect", "es" to "Conectar", "fr" to "Connecter",
            "de" to "Verbinden", "pt" to "Conectar", "it" to "Connetti",
            "ja" to "接続", "zh" to "连接", "hi" to "कनेक्ट", "ar" to "اتصال"),
        "tab.manage" to mapOf(
            "en" to "Manage", "es" to "Gestionar", "fr" to "Gérer",
            "de" to "Verwalten", "pt" to "Gerenciar", "it" to "Gestisci",
            "ja" to "管理", "zh" to "管理", "hi" to "प्रबंधन", "ar" to "إدارة"),
        "tab.settings" to mapOf(
            "en" to "Settings", "es" to "Ajustes", "fr" to "Réglages",
            "de" to "Einstellungen", "pt" to "Configurações", "it" to "Impostazioni",
            "ja" to "設定", "zh" to "设置", "hi" to "सेटिंग्स", "ar" to "الإعدادات"),
        "action.send" to mapOf(
            "en" to "Send", "es" to "Enviar", "fr" to "Envoyer",
            "de" to "Senden", "pt" to "Enviar", "it" to "Invia",
            "ja" to "送信", "zh" to "发送", "hi" to "भेजें", "ar" to "إرسال"),
        "action.save" to mapOf(
            "en" to "Save", "es" to "Guardar", "fr" to "Enregistrer",
            "de" to "Speichern", "pt" to "Salvar", "it" to "Salva",
            "ja" to "保存", "zh" to "保存", "hi" to "सहेजें", "ar" to "حفظ"),
        "action.translate" to mapOf(
            "en" to "Translate", "es" to "Traducir", "fr" to "Traduire",
            "de" to "Übersetzen", "pt" to "Traduzir", "it" to "Traduci",
            "ja" to "翻訳", "zh" to "翻译", "hi" to "अनुवाद", "ar" to "ترجمة"),
        "action.sign_out" to mapOf(
            "en" to "Sign out", "es" to "Cerrar sesión", "fr" to "Se déconnecter",
            "de" to "Abmelden", "pt" to "Sair", "it" to "Esci",
            "ja" to "サインアウト", "zh" to "退出登录", "hi" to "साइन आउट",
            "ar" to "تسجيل الخروج"),
        "action.refresh" to mapOf(
            "en" to "Refresh", "es" to "Actualizar", "fr" to "Actualiser",
            "de" to "Aktualisieren", "pt" to "Atualizar", "it" to "Aggiorna",
            "ja" to "更新", "zh" to "刷新", "hi" to "रीफ़्रेश", "ar" to "تحديث"),

        // -- The accountless screen ----------------------------------------
        //
        // Ported from the console's `pub.*` rows rather than translated
        // again: one product says one thing, and a second translation of the
        // same sentence is a second thing to keep in step. The four keys the
        // console has no row for name UI only a shell has — a sheet's dismiss
        // button, two client-side validation lines and a placeholder.
        "pub.sub" to mapOf("en" to "Without an account", "es" to "Sin cuenta", "fr" to "Sans compte", "de" to "Ohne Konto", "pt" to "Sem conta", "it" to "Senza account", "ja" to "アカウントなしで", "zh" to "无需账户", "hi" to "बिना खाते के", "ar" to "بدون حساب"),
        "pub.invite" to mapOf("en" to "Here about a profile, not for one?", "es" to "¿Viene por un perfil, no a crear uno?", "fr" to "Ici à propos d'un profil, pas pour en créer un ?", "de" to "Wegen eines Profils hier, nicht für eines?", "pt" to "Está aqui por causa de um perfil, não para criar um?", "it" to "Sei qui per un profilo, non per crearne uno?", "ja" to "プロフィールを作りに来たのではなく、あるプロフィールの件でしょうか？", "zh" to "你是为某个资料而来，而不是来创建一个？", "hi" to "किसी प्रोफ़ाइल के बारे में आए हैं, बनाने नहीं?", "ar" to "أتيت بشأن ملف، لا لإنشاء واحد؟"),
        "pub.invite.none" to mapOf("en" to "Neither needs an account.", "es" to "Ninguna de las dos necesita cuenta.", "fr" to "Aucun des deux ne nécessite de compte.", "de" to "Für beides ist kein Konto nötig.", "pt" to "Nenhuma das duas precisa de conta.", "it" to "Nessuna delle due richiede un account.", "ja" to "どちらもアカウントは不要です。", "zh" to "两者都不需要账户。", "hi" to "दोनों के लिए खाता ज़रूरी नहीं।", "ar" to "لا يحتاج أيٌّ منهما إلى حساب."),
        "pub.object.title" to mapOf("en" to "A profile depicts me", "es" to "Un perfil me representa", "fr" to "Un profil me représente", "de" to "Ein Profil stellt mich dar", "pt" to "Um perfil representa-me", "it" to "Un profilo mi rappresenta", "ja" to "私を模したプロフィールがあります", "zh" to "有一个资料在描绘我", "hi" to "एक प्रोफ़ाइल मुझे दर्शाती है", "ar" to "هناك ملف يصوّرني"),
        "pub.tab.mark" to mapOf("en" to "Is this genuine?", "es" to "¿Esto es auténtico?", "fr" to "Est-ce authentique ?", "de" to "Ist das echt?", "pt" to "Isto é genuíno?", "it" to "È autentico?", "ja" to "これは本物ですか？", "zh" to "这是真的吗？", "hi" to "क्या यह असली है?", "ar" to "هل هذا أصلي؟"),
        "pub.object.restricts" to mapOf("en" to "You do not need an account, and this page is the proof of it rather than a promise about it. Opening an objection restricts the profile straight away — public surfaces off, no new interactors — before anybody reviews it.", "es" to "No necesita una cuenta, y esta página es la prueba de ello, no una promesa al respecto. Abrir una objeción restringe el perfil de inmediato —superficies públicas desactivadas, sin nuevos interlocutores— antes de que nadie lo revise.", "fr" to "Vous n'avez pas besoin de compte, et cette page en est la preuve plutôt qu'une promesse. Ouvrir une contestation restreint le profil immédiatement — surfaces publiques coupées, aucun nouvel interlocuteur — avant tout examen.", "de" to "Sie brauchen kein Konto, und diese Seite ist der Beweis dafür statt eines Versprechens darüber. Ein Widerspruch beschränkt das Profil sofort — öffentliche Flächen aus, keine neuen Gesprächspartner — noch bevor jemand es prüft.", "pt" to "Não precisa de conta, e esta página é a prova disso e não uma promessa sobre isso. Abrir uma contestação restringe o perfil de imediato — superfícies públicas desligadas, sem novos interlocutores — antes de alguém a analisar.", "it" to "Non serve un account, e questa pagina ne è la prova anziché una promessa. Aprire una contestazione limita subito il profilo — superfici pubbliche spente, nessun nuovo interlocutore — prima che qualcuno la esamini.", "ja" to "アカウントは不要です。このページはその約束ではなく、その証拠です。異議を申し立てると、誰かが審査する前に、プロフィールは直ちに制限されます（公開面は停止、新しい相手とのやり取りも停止）。", "zh" to "你不需要账户，本页面就是证明，而不是关于它的承诺。提出异议会立即限制该资料 — 关闭公开界面、不再接受新的互动对象 — 在任何人审核之前。", "hi" to "आपको खाते की ज़रूरत नहीं, और यह पृष्ठ उसका वादा नहीं बल्कि प्रमाण है। आपत्ति दर्ज करते ही प्रोफ़ाइल तुरंत सीमित हो जाती है — सार्वजनिक सतहें बंद, कोई नया संवादकर्ता नहीं — किसी की समीक्षा से पहले।", "ar" to "لا تحتاج إلى حساب، وهذه الصفحة هي الدليل على ذلك لا وعدًا به. فتح اعتراض يقيّد الملف فورًا — إيقاف الواجهات العامة، ولا متفاعلين جدد — قبل أن يراجعه أحد."),
        "pub.object.profileId" to mapOf("en" to "the profile's id", "es" to "el id del perfil", "fr" to "l'identifiant du profil", "de" to "die ID des Profils", "pt" to "o id do perfil", "it" to "l'id del profilo", "ja" to "プロフィールのID", "zh" to "该资料的 id", "hi" to "प्रोफ़ाइल की आईडी", "ar" to "معرّف الملف"),
        "pub.object.ref" to mapOf("en" to "your proof reference", "es" to "su referencia de prueba", "fr" to "votre référence de preuve", "de" to "Ihr Nachweis-Aktenzeichen", "pt" to "a sua referência de prova", "it" to "il tuo riferimento di prova", "ja" to "本人確認の参照番号", "zh" to "你的证明编号", "hi" to "आपका प्रमाण संदर्भ", "ar" to "مرجع إثباتك"),
        "pub.object.reason" to mapOf("en" to "why — in your own words", "es" to "por qué — con sus palabras", "fr" to "pourquoi — avec vos mots", "de" to "warum — in Ihren eigenen Worten", "pt" to "porquê — nas suas palavras", "it" to "perché — con parole tue", "ja" to "理由 — ご自身の言葉で", "zh" to "原因 — 用你自己的话", "hi" to "क्यों — अपने शब्दों में", "ar" to "لماذا — بكلماتك"),
        "pub.object.ref.note" to mapOf("en" to "The proof reference points at an identity check held outside this system — it is not a login, and it is what lets you object without one.", "es" to "La referencia de prueba apunta a una comprobación de identidad realizada fuera de este sistema: no es un inicio de sesión, y es lo que le permite objetar sin tener uno.", "fr" to "La référence de preuve renvoie à une vérification d'identité effectuée hors de ce système : ce n'est pas une connexion, et c'est ce qui vous permet de contester sans en avoir une.", "de" to "Das Nachweis-Aktenzeichen verweist auf eine Identitätsprüfung außerhalb dieses Systems — es ist keine Anmeldung, und genau deshalb können Sie ohne eine widersprechen.", "pt" to "A referência de prova aponta para uma verificação de identidade feita fora deste sistema: não é um início de sessão, e é o que lhe permite contestar sem ter um.", "it" to "Il riferimento di prova rimanda a una verifica d'identità tenuta fuori da questo sistema: non è un accesso, ed è ciò che ti permette di contestare senza averne uno.", "ja" to "参照番号は、この仕組みの外で行われた本人確認を指します。ログインではなく、ログインなしで異議を申し立てられるようにするためのものです。", "zh" to "证明编号指向在本系统之外完成的身份核验 — 它不是登录凭据，正是它让你无需登录也能提出异议。", "hi" to "प्रमाण संदर्भ इस प्रणाली के बाहर हुई पहचान-जाँच की ओर इशारा करता है — यह लॉगिन नहीं है, और यही आपको बिना लॉगिन के आपत्ति दर्ज करने देता है।", "ar" to "مرجع الإثبات يشير إلى تحقّق من الهوية جرى خارج هذا النظام — ليس تسجيل دخول، وهو ما يتيح لك الاعتراض بدونه."),
        "pub.object.open" to mapOf("en" to "Open it", "es" to "Abrirla", "fr" to "L'ouvrir", "de" to "Einreichen", "pt" to "Abrir", "it" to "Aprila", "ja" to "申し立てる", "zh" to "提出", "hi" to "दर्ज करें", "ar" to "افتحه"),
        "pub.object.opened" to mapOf("en" to "Opened — {id}", "es" to "Abierta — {id}", "fr" to "Ouverte — {id}", "de" to "Eröffnet — {id}", "pt" to "Aberta — {id}", "it" to "Aperta — {id}", "ja" to "受付済み — {id}", "zh" to "已提出 — {id}", "hi" to "दर्ज — {id}", "ar" to "فُتح — {id}"),
        "pub.object.opened.status" to mapOf("en" to "The profile is {now} from this moment. It was {before}, and if the objection is dismissed it goes back to exactly that.", "es" to "El perfil queda {now} desde este momento. Era {before}, y si la objeción se desestima vuelve exactamente a eso.", "fr" to "Le profil est {now} à partir de maintenant. Il était {before}, et si la contestation est rejetée il y revient exactement.", "de" to "Das Profil ist ab sofort {now}. Es war {before}, und wenn der Widerspruch abgewiesen wird, kehrt es genau dorthin zurück.", "pt" to "O perfil fica {now} a partir deste momento. Era {before}, e se a contestação for rejeitada volta exatamente a isso.", "it" to "Il profilo è {now} da questo momento. Era {before}, e se la contestazione viene respinta torna esattamente a quello.", "ja" to "プロフィールはこの時点から {now} になります。それまでは {before} でした。異議が棄却されれば、そのままの状態に戻ります。", "zh" to "该资料从此刻起为 {now}。此前是 {before}；若异议被驳回，将完全恢复原状。", "hi" to "इस क्षण से प्रोफ़ाइल {now} है। यह {before} थी, और यदि आपत्ति खारिज होती है तो वह ठीक वैसी ही हो जाएगी।", "ar" to "الملف {now} اعتبارًا من هذه اللحظة. كان {before}، وإذا رُفض الاعتراض عاد إلى ذلك تمامًا."),
        "pub.object.writeitdown" to mapOf("en" to "Write the id down. It is how you check this case later without an account — there is no inbox here to come back to.", "es" to "Anote el identificador. Es cómo consultará este caso más adelante sin una cuenta: aquí no hay bandeja de entrada a la que volver.", "fr" to "Notez l'identifiant. C'est ainsi que vous suivrez ce dossier plus tard sans compte : il n'y a pas de boîte de réception ici où revenir.", "de" to "Notieren Sie die ID. So prüfen Sie diesen Fall später ohne Konto — hier gibt es keinen Posteingang, zu dem Sie zurückkehren könnten.", "pt" to "Anote o id. É assim que consultará este caso mais tarde sem conta — aqui não há caixa de entrada para onde voltar.", "it" to "Annota l'id. È così che controllerai questo caso più avanti senza un account: qui non c'è una casella a cui tornare.", "ja" to "IDを控えてください。アカウントなしで後からこの件を確認する唯一の方法です。戻ってこられる受信箱はありません。", "zh" to "请记下这个 id。这是你日后在没有账户的情况下查询本案的方式 — 这里没有可供你回来查看的收件箱。", "hi" to "यह आईडी लिख लें। बिना खाते के बाद में इस मामले को देखने का यही तरीका है — यहाँ लौटने के लिए कोई इनबॉक्स नहीं है।", "ar" to "دوّن المعرّف. فهو كيف تتابع هذه القضية لاحقًا بدون حساب — لا يوجد هنا صندوق وارد تعود إليه."),
        "pub.mark.title" to mapOf("en" to "Somebody sent me this", "es" to "Alguien me envió esto", "fr" to "Quelqu'un m'a envoyé ceci", "de" to "Jemand hat mir das geschickt", "pt" to "Alguém enviou-me isto", "it" to "Qualcuno mi ha mandato questo", "ja" to "これを送られてきました", "zh" to "有人给我发了这个", "hi" to "किसी ने मुझे यह भेजा", "ar" to "أرسل لي أحدهم هذا"),
        "pub.mark.explain" to mapOf("en" to "Paste it. This asks whose work it is with no credential id, and keeps answering after the text has been reworded — which is the state text usually arrives in. It is the right question for a stranger holding a screenshot; checking a credential you already hold is a different one and lives inside an account.", "es" to "Péguelo. Esto pregunta de quién es el trabajo sin ningún identificador de credencial, y sigue respondiendo después de que el texto haya sido reescrito, que es el estado en el que suele llegar. Es la pregunta correcta para un desconocido con una captura de pantalla; comprobar una credencial que ya tiene es otra distinta y vive dentro de una cuenta.", "fr" to "Collez-le. Ceci demande à qui appartient le contenu sans aucun identifiant de justificatif, et répond encore après reformulation du texte — l'état dans lequel il arrive le plus souvent. C'est la bonne question pour un inconnu tenant une capture d'écran ; vérifier un justificatif que vous détenez déjà en est une autre, et elle vit dans un compte.", "de" to "Fügen Sie ihn ein. Das fragt, wessen Werk es ist, ohne jede Credential-ID, und antwortet auch noch, nachdem der Text umformuliert wurde — der Zustand, in dem Text meist ankommt. Es ist die richtige Frage für eine fremde Person mit einem Screenshot; ein Nachweis, den Sie bereits halten, ist eine andere Frage und lebt in einem Konto.", "pt" to "Cole-o. Isto pergunta de quem é o trabalho sem qualquer identificador de credencial, e continua respondendo depois de o texto ter sido reescrito — o estado em que o texto costuma chegar. É a pergunta certa para um desconhecido com uma captura de tela; verificar uma credencial que você já possui é outra e vive dentro de uma conta.", "it" to "Incollalo. Questo chiede di chi è il lavoro senza alcun identificativo di credenziale, e continua a rispondere dopo che il testo è stato riformulato — lo stato in cui il testo di solito arriva. È la domanda giusta per uno sconosciuto con uno screenshot; verificare una credenziale che già possiedi è un'altra cosa e vive dentro un account.", "ja" to "貼り付けてください。これは資格情報の ID なしに、それが誰の作かを尋ねます。文章が書き換えられた後でも答え続けます — 実際に届く文章はたいていその状態です。スクリーンショットを手にした見知らぬ人にとって正しい問いです。すでに持っている資格情報を確認するのは別の問いで、それはアカウントの中にあります。", "zh" to "粘贴进来。这会在不需要任何凭据 ID 的情况下询问它出自谁手，并且在文本被改写之后仍能作答 — 而文本通常正是以这种状态出现的。对于手持截图的陌生人，这是正确的问题；核验你已经持有的凭据是另一个问题，它属于账户内部。", "hi" to "इसे चिपकाएँ। यह बिना किसी क्रेडेंशियल आईडी के पूछता है कि यह किसका काम है, और पाठ के शब्द बदल दिए जाने के बाद भी उत्तर देता रहता है — पाठ आम तौर पर इसी हालत में पहुँचता है। स्क्रीनशॉट थामे किसी अजनबी के लिए यही सही सवाल है; जो क्रेडेंशियल आपके पास पहले से है उसे जाँचना अलग सवाल है और वह खाते के भीतर रहता है।", "ar" to "الصقه هنا. هذا يسأل عن صاحب العمل دون أي معرّف اعتماد، ويظل يجيب بعد إعادة صياغة النص — وهي الحالة التي يصل بها النص عادةً. إنه السؤال الصحيح لغريب يحمل لقطة شاشة؛ أما التحقق من اعتماد تملكه بالفعل فسؤال آخر يعيش داخل حساب."),
        "pub.mark.paste" to mapOf("en" to "paste the text", "es" to "pegue el texto", "fr" to "collez le texte", "de" to "Text einfügen", "pt" to "cole o texto", "it" to "incolla il testo", "ja" to "テキストを貼り付けてください", "zh" to "粘贴文本", "hi" to "पाठ चिपकाएँ", "ar" to "الصق النص"),
        "pub.mark.ask" to mapOf("en" to "Ask who wrote it", "es" to "Preguntar quién lo escribió", "fr" to "Demander qui l'a écrit", "de" to "Fragen, wer es geschrieben hat", "pt" to "Perguntar quem o escreveu", "it" to "Chiedi chi l'ha scritto", "ja" to "誰が書いたか調べる", "zh" to "查询是谁写的", "hi" to "पूछें किसने लिखा", "ar" to "اسأل من كتبه"),
        "pub.mark.producedby" to mapOf("en" to "Produced by a QRME synthetic profile — {state}.", "es" to "Producido por un perfil sintético de QRME — {state}.", "fr" to "Produit par un profil synthétique QRME — {state}.", "de" to "Erzeugt von einem synthetischen QRME-Profil — {state}.", "pt" to "Produzido por um perfil sintético do QRME — {state}.", "it" to "Prodotto da un profilo sintetico QRME — {state}.", "ja" to "QRME の合成プロフィールによる生成物 — {state}。", "zh" to "由 QRME 合成资料生成 — {state}。", "hi" to "QRME की सिंथेटिक प्रोफ़ाइल द्वारा निर्मित — {state}।", "ar" to "من إنتاج ملف اصطناعي في QRME — {state}."),
        "pub.mark.windows" to mapOf("en" to "{matched} of {stored} stored windows matched, out of {examined} examined (similarity {similarity}).", "es" to "Coincidieron {matched} de {stored} ventanas almacenadas, de {examined} examinadas (similitud {similarity}).", "fr" to "{matched} fenêtres enregistrées sur {stored} correspondent, sur {examined} examinées (similarité {similarity}).", "de" to "{matched} von {stored} gespeicherten Fenstern stimmten überein, bei {examined} geprüften (Ähnlichkeit {similarity}).", "pt" to "Coincidiram {matched} de {stored} janelas armazenadas, entre {examined} examinadas (similaridade {similarity}).", "it" to "Hanno corrisposto {matched} finestre su {stored} memorizzate, su {examined} esaminate (somiglianza {similarity}).", "ja" to "保存済み {stored} 個のウィンドウのうち {matched} 個が一致しました（検査対象 {examined} 個、類似度 {similarity}）。", "zh" to "在 {examined} 个受检窗口中，已存储的 {stored} 个窗口有 {matched} 个匹配（相似度 {similarity}）。", "hi" to "संग्रहीत {stored} विंडो में से {matched} मेल खाईं, कुल {examined} जाँची गईं (समानता {similarity})।", "ar" to "تطابقت {matched} من أصل {stored} نافذة مخزّنة، من بين {examined} جرى فحصها (التشابه {similarity})."),
        "pub.mark.altered" to mapOf("en" to "The wording has changed since it was stamped. That does not make it less traceable — it is what the score above is measuring.", "es" to "La redacción ha cambiado desde que se selló. Eso no lo hace menos rastreable: es precisamente lo que mide la puntuación anterior.", "fr" to "La formulation a changé depuis l'horodatage. Cela ne le rend pas moins traçable : c'est justement ce que mesure le score ci-dessus.", "de" to "Der Wortlaut hat sich seit der Kennzeichnung geändert. Das macht ihn nicht weniger nachverfolgbar — genau das misst der Wert oben.", "pt" to "A redação mudou desde que foi selada. Isso não a torna menos rastreável: é precisamente o que a pontuação acima mede.", "it" to "Il testo è cambiato da quando è stato marcato. Questo non lo rende meno tracciabile: è proprio ciò che il punteggio sopra misura.", "ja" to "刻印されてから文言が変わっています。それで追跡できなくなるわけではありません。上のスコアが測っているのはまさにその差です。", "zh" to "自加盖标记以来措辞已经改变。这并不会让它更难追溯 — 上面的分数衡量的正是这一点。", "hi" to "मुहर लगने के बाद शब्द बदले हैं। इससे यह कम पता लगाने योग्य नहीं होता — ऊपर का स्कोर यही माप रहा है।", "ar" to "تغيّرت الصياغة منذ ختمه. هذا لا يجعله أقل قابلية للتتبّع — فذلك تحديدًا ما تقيسه الدرجة أعلاه."),
        "pub.mark.unknown" to mapOf("en" to "Not recognised", "es" to "No reconocido", "fr" to "Non reconnu", "de" to "Nicht erkannt", "pt" to "Não reconhecido", "it" to "Non riconosciuto", "ja" to "該当なし", "zh" to "未识别", "hi" to "पहचाना नहीं गया", "ar" to "غير معروف"),
        "pub.mark.unknown.explain" to mapOf("en" to "This says nothing about whether a person wrote it. It says no profile {here} has stamped work that shares enough wording with it.", "es" to "Esto no dice nada sobre si lo escribió una persona. Dice que ningún perfil {here} ha firmado un trabajo que comparta suficiente redacción con él.", "fr" to "Cela ne dit rien sur le fait qu'une personne l'ait écrit. Cela dit qu'aucun profil {here} n'a signé un contenu partageant assez de formulations avec lui.", "de" to "Das sagt nichts darüber, ob ein Mensch es geschrieben hat. Es sagt, dass kein Profil {here} eine Arbeit gestempelt hat, die genug Wortlaut mit ihr teilt.", "pt" to "Isto não diz nada sobre se uma pessoa o escreveu. Diz que nenhum perfil {here} carimbou um trabalho que partilhe redação suficiente com ele.", "it" to "Questo non dice nulla sul fatto che l'abbia scritto una persona. Dice che nessun profilo {here} ha timbrato un lavoro che condivida abbastanza formulazioni con esso.", "ja" to "これは人が書いたかどうかについては何も述べていません。{here}、これと十分に語句を共有する作品に印を付けたプロフィールが存在しない、という意味です。", "zh" to "这并不说明它是否由人所写。它说明的是：{here}没有任何资料曾为与之用词足够相近的作品加过标记。", "hi" to "इससे यह पता नहीं चलता कि इसे किसी व्यक्ति ने लिखा या नहीं। इसका अर्थ है कि {here} किसी प्रोफ़ाइल ने ऐसा काम मुहरबंद नहीं किया जिसकी शब्दावली इससे पर्याप्त मेल खाती हो।", "ar" to "هذا لا يقول شيئًا عمّا إذا كان قد كتبه إنسان. إنه يقول إنه ما من ملف {here} ختم عملًا يشترك معه في ما يكفي من الصياغة."),
        "pub.mark.here" to mapOf("en" to "on this deployment", "es" to "en esta instalación", "fr" to "sur ce déploiement", "de" to "auf dieser Installation", "pt" to "nesta instalação", "it" to "su questa installazione", "ja" to "この環境で", "zh" to "在本部署中", "hi" to "इस परिनियोजन पर", "ar" to "في هذا التنصيب"),
        "pub.notoken" to mapOf("en" to "Nothing on this page reads or needs a token.", "es" to "Nada en esta página lee ni necesita una credencial.", "fr" to "Rien sur cette page ne lit ni ne requiert d'identifiant.", "de" to "Nichts auf dieser Seite liest oder braucht ein Token.", "pt" to "Nada nesta página lê ou precisa de uma credencial.", "it" to "Nulla in questa pagina legge o richiede una credenziale.", "ja" to "このページは資格情報を読み取らず、必要ともしません。", "zh" to "本页面既不读取也不需要任何凭据。", "hi" to "इस पृष्ठ पर कुछ भी टोकन नहीं पढ़ता और न ही चाहिए।", "ar" to "لا شيء في هذه الصفحة يقرأ رمزًا أو يحتاج إليه."),
        "pub.state.active" to mapOf("en" to "active", "es" to "activo", "fr" to "actif", "de" to "aktiv", "pt" to "ativo", "it" to "attivo", "ja" to "有効", "zh" to "有效", "hi" to "सक्रिय", "ar" to "نشط"),
        "pub.state.restricted" to mapOf("en" to "restricted", "es" to "restringido", "fr" to "restreint", "de" to "beschränkt", "pt" to "restringido", "it" to "limitato", "ja" to "制限中", "zh" to "受限", "hi" to "सीमित", "ar" to "مقيَّد"),
        "pub.state.departed" to mapOf("en" to "departed", "es" to "fallecido", "fr" to "disparu", "de" to "verstorben", "pt" to "falecido", "it" to "scomparso", "ja" to "故人", "zh" to "已故", "hi" to "दिवंगत", "ar" to "متوفى"),
        "pub.state.terminated" to mapOf("en" to "terminated", "es" to "terminado", "fr" to "supprimé", "de" to "beendet", "pt" to "terminado", "it" to "terminato", "ja" to "終了", "zh" to "已终止", "hi" to "समाप्त", "ar" to "مُنهى"),
        "pub.back.short" to mapOf("en" to "Back", "es" to "Atrás", "fr" to "Retour", "de" to "Zurück", "pt" to "Voltar", "it" to "Indietro", "ja" to "戻る", "zh" to "返回", "hi" to "वापस", "ar" to "رجوع"),
        "pub.object.needid" to mapOf("en" to "Enter the profile's id and your proof reference.", "es" to "Introduzca el id del perfil y su referencia de prueba.", "fr" to "Saisissez l'identifiant du profil et votre référence de preuve.", "de" to "Geben Sie die Profil-ID und Ihre Nachweisreferenz ein.", "pt" to "Introduza o id do perfil e a sua referência de prova.", "it" to "Inserisci l'id del profilo e il tuo riferimento di prova.", "ja" to "プロフィールIDと証明の参照番号を入力してください。", "zh" to "请输入资料 id 和你的证明参考号。", "hi" to "प्रोफ़ाइल आईडी और अपना प्रमाण संदर्भ दर्ज करें।", "ar" to "أدخل معرّف الملف ومرجع إثباتك."),
        "pub.mark.needtext" to mapOf("en" to "Paste the text first.", "es" to "Pegue primero el texto.", "fr" to "Collez d'abord le texte.", "de" to "Fügen Sie zuerst den Text ein.", "pt" to "Cole primeiro o texto.", "it" to "Incolla prima il testo.", "ja" to "先にテキストを貼り付けてください。", "zh" to "请先粘贴文本。", "hi" to "पहले पाठ चिपकाएँ।", "ar" to "الصق النص أولاً."),
        "pub.object.ref.ph" to mapOf("en" to "an identity check held elsewhere", "es" to "una verificación de identidad hecha en otro sitio", "fr" to "une vérification d'identité conservée ailleurs", "de" to "eine anderswo geführte Identitätsprüfung", "pt" to "uma verificação de identidade guardada noutro lado", "it" to "una verifica d'identità conservata altrove", "ja" to "他所で行われた本人確認", "zh" to "在别处完成的身份验证", "hi" to "कहीं और रखी गई पहचान जाँच", "ar" to "تحقّق من الهوية محفوظ في مكان آخر"),
        "people.friends" to mapOf("en" to "Friends", "es" to "Amigos", "fr" to "Amis", "de" to "Freunde", "pt" to "Amigos", "it" to "Amici", "ja" to "友だち", "zh" to "好友", "hi" to "दोस्त", "ar" to "الأصدقاء"),
        "people.pinned" to mapOf("en" to "pinned", "es" to "fijado", "fr" to "épinglé", "de" to "angeheftet", "pt" to "fixado", "it" to "fissato", "ja" to "固定", "zh" to "已固定", "hi" to "पिन किया", "ar" to "مثبّت"),
        "people.remove" to mapOf("en" to "Remove", "es" to "Quitar", "fr" to "Retirer", "de" to "Entfernen", "pt" to "Remover", "it" to "Rimuovi", "ja" to "削除", "zh" to "移除", "hi" to "हटाएँ", "ar" to "إزالة"),
        "people.add" to mapOf("en" to "Their profile id", "es" to "Su id de perfil", "fr" to "Leur identifiant de profil", "de" to "Deren Profil-ID", "pt" to "O id de perfil deles", "it" to "Il loro id profilo", "ja" to "相手のプロフィールID", "zh" to "对方的资料 id", "hi" to "उनकी प्रोफ़ाइल आईडी", "ar" to "معرّف ملفهم"),
        "people.add.go" to mapOf("en" to "Add", "es" to "Añadir", "fr" to "Ajouter", "de" to "Hinzufügen", "pt" to "Adicionar", "it" to "Aggiungi", "ja" to "追加", "zh" to "添加", "hi" to "जोड़ें", "ar" to "إضافة"),
        "people.suggested" to mapOf("en" to "People you might know", "es" to "Personas que quizá conozcas", "fr" to "Des personnes que vous connaissez peut-être", "de" to "Leute, die du kennen könntest", "pt" to "Pessoas que talvez conheça", "it" to "Persone che potresti conoscere", "ja" to "知り合いかもしれない人", "zh" to "你可能认识的人", "hi" to "जिन्हें आप जानते होंगे", "ar" to "أشخاص قد تعرفهم"),
        "people.ranked" to mapOf("en" to "Ranked on friends in common and shared subjects — never on source material, memories or anything vaulted.", "es" to "Ordenado por amigos en común y temas compartidos — nunca por material de origen, recuerdos ni nada guardado en la bóveda.", "fr" to "Classé selon les amis en commun et les sujets partagés — jamais selon les sources, les souvenirs ou le coffre.", "de" to "Sortiert nach gemeinsamen Freunden und Themen — nie nach Quellmaterial, Erinnerungen oder Tresorinhalten.", "pt" to "Ordenado por amigos em comum e temas partilhados — nunca por material de origem, memórias ou o cofre.", "it" to "Ordinato per amici in comune e argomenti condivisi — mai per materiale sorgente, ricordi o contenuti del caveau.", "ja" to "共通の友だちと共通のテーマで並びます — 元資料や記憶、保管庫の中身は使いません。", "zh" to "依据共同好友与共同主题排序 — 绝不依据原始素材、记忆或保险库内容。", "hi" to "साझा दोस्तों और साझा विषयों पर क्रम — स्रोत सामग्री, यादों या तिजोरी पर कभी नहीं।", "ar" to "مرتّب حسب الأصدقاء المشتركين والمواضيع المشتركة — لا حسب المواد المصدرية أو الذكريات أو الخزنة."),
        "people.wall" to mapOf("en" to "The wall", "es" to "El muro", "fr" to "Le mur", "de" to "Die Pinnwand", "pt" to "O mural", "it" to "La bacheca", "ja" to "ウォール", "zh" to "留言墙", "hi" to "दीवार", "ar" to "الحائط"),
        "people.say" to mapOf("en" to "Say something", "es" to "Di algo", "fr" to "Dites quelque chose", "de" to "Sag etwas", "pt" to "Diga algo", "it" to "Di qualcosa", "ja" to "何か書く", "zh" to "说点什么", "hi" to "कुछ कहें", "ar" to "قل شيئًا"),
        "people.post" to mapOf("en" to "Post", "es" to "Publicar", "fr" to "Publier", "de" to "Posten", "pt" to "Publicar", "it" to "Pubblica", "ja" to "投稿", "zh" to "发布", "hi" to "पोस्ट करें", "ar" to "نشر"),
        "people.blocked" to mapOf("en" to "Held by moderation — visible to you alone", "es" to "Retenido por moderación — visible solo para ti", "fr" to "Retenu par la modération — visible de vous seul", "de" to "Von der Moderation zurückgehalten — nur für dich sichtbar", "pt" to "Retido pela moderação — visível apenas para si", "it" to "Trattenuto dalla moderazione — visibile solo a te", "ja" to "モデレーションにより保留 — あなただけに表示されます", "zh" to "已被审核拦截 — 仅你可见", "hi" to "मॉडरेशन ने रोका — केवल आपको दिखता है", "ar" to "محجوز بالإشراف — مرئي لك وحدك"),
        "people.comments" to mapOf("en" to "Comments", "es" to "Comentarios", "fr" to "Commentaires", "de" to "Kommentare", "pt" to "Comentários", "it" to "Commenti", "ja" to "コメント", "zh" to "评论", "hi" to "टिप्पणियाँ", "ar" to "التعليقات"),
        "people.reply" to mapOf("en" to "Write a comment", "es" to "Escribe un comentario", "fr" to "Écrivez un commentaire", "de" to "Schreibe einen Kommentar", "pt" to "Escreva um comentário", "it" to "Scrivi un commento", "ja" to "コメントを書く", "zh" to "写评论", "hi" to "टिप्पणी लिखें", "ar" to "اكتب تعليقًا"),
        "people.send" to mapOf("en" to "Send", "es" to "Enviar", "fr" to "Envoyer", "de" to "Senden", "pt" to "Enviar", "it" to "Invia", "ja" to "送信", "zh" to "发送", "hi" to "भेजें", "ar" to "إرسال"),
        "people.withdraw" to mapOf("en" to "Withdraw", "es" to "Retirar", "fr" to "Retirer", "de" to "Zurückziehen", "pt" to "Retirar", "it" to "Ritira", "ja" to "取り消す", "zh" to "撤回", "hi" to "वापस लें", "ar" to "سحب"),
    )
}
